### PR TITLE
QtAboutKeyBindings patch

### LINKED ISSUE #2128: Show Key Bindings menu option is not working in Napari 0.4.3
## 🐛 Bug

The Show Key Bindings menu option is not working.

## To Reproduce

1. Click on the Help menubar option
2. Then, click on Show Key Bindings

## Expected behavior

I would expect to see a list of all the available Key Bindings

## Environment

napari: 0.4.3
Platform: Linux-4.15.0-55-generic-x86_64-with-glibc2.10
Python: 3.8.3 (default, Jul 2 2020, 16:21:59) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2021.01.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.27.04
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen #1: resolution 1920x1080, scale 1.0

Plugins:
- napari_plugin_engine: 0.1.9
- svg: 0.1.4

 - Any other relevant information:

#### Error message:

/opt/Installers/python3.8/site-packages/napari/_qt/qt_viewer.py", line 576, in show_key_bindings_dialog
    dialog = QtAboutKeyBindings(self.viewer, parent=self)
  File "/opt/Installers/python3.8/site-packages/napari/_qt/dialogs/qt_about_key_bindings.py", line 67, in __init__
    theme = get_theme(self.qt_viewer.viewer.theme)
AttributeError: 'QtAboutKeyBindings' object has no attribute 'qt_viewer'

### PR DESCRIPTION
**Pull request by nhthayer**
# Description

This should restore the ability to open the QtAboutKeyBindings dialog window. See #2128.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

closes #2128, implemented fix as suggested by @sofroniewn in the issue. 

# How has this been tested?

- [x] all existing tests pass (or are skipped) with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Code changes look great! For the tests you can you model after the beginning of this one https://github.com/napari/napari/blob/2d570b946fc5bb91d323f1787d5deb0053cb70a9/napari/_qt/_tests/test_qt_viewer.py#L16-L19

and do something like

```python
viewer = make_test_viewer()
view = viewer.window.qt_viewer
key_bindings_dialog = QtAboutKeyBindings(viewer, view. _key_map_handler)
# check methods like key_bindings_dialog.update_active_layer() etc.
```

and 

```python
viewer = make_test_viewer()
view = viewer.window.qt_viewer
view.show_key_bindings_dialog()
```

and check that the objects exist. One could get fancier and then check doing things like changing the active layer changes they displayed keybindings, but these tests will already be better than nothing!!

**Comment by sofroniewn** [comment]
This windows CI fail is likely unrelated to this PR and something we are seeing on other PRs too right now

**Comment by nhthayer** [comment]
I tried adding a test like: 
```python
def test_show_key_bindings_dialog(make_test_viewer):
    """Test creating dialog with method of qt_viewer."""
    viewer = make_test_viewer()
    view = viewer.window.qt_viewer
    view.show_key_bindings_dialog()
 ```

However, this caused the window to flash up while running the tests, so I omitted it from the commit. Assuming this is because `show_key_bindings_dialog` calls `dialog.show()`: 
https://github.com/napari/napari/blob/42701623e9f21a7e37a4fe44d5e0dcdac1a66c6c/napari/_qt/qt_viewer.py#L575-L578

**Comment by tlambert03** [comment]
> However, this caused the window to flash up while running the tests, so I omitted it from the commit. Assuming this is because `show_key_bindings_dialog` calls `dialog.show()`:

one option here is to monkeypatch only that method... see this line in test_examples for an example.

https://github.com/napari/napari/blob/2d570b946fc5bb91d323f1787d5deb0053cb70a9/napari/_tests/test_examples.py#L48-L49

**Comment by sofroniewn** [comment]
> monkeypatch only that method

That sounds like a good idea.

I've just realized that we should add a test that checks that the keybindings update properly when the active layer changes, as we might be subject to a race condition here with our event system as `viewer.events.active_layer` triggers both the `key_map_handler` update and this dialog update - which now has to happen after the `key_map_handler` update!

**Comment by nhthayer** [comment]
https://github.com/napari/napari/blob/42701623e9f21a7e37a4fe44d5e0dcdac1a66c6c/napari/_qt/qt_viewer.py#L67-L68

It looks like `aboutKeybindings` was previously an attribute of `QtViewer`, and is still in the docstring as such. 

Should this simply removed from the docstring, or should this reference be restored? Make it a property?

**Comment by sofroniewn** [comment]
> It looks like aboutKeybindings was previously an attribute of QtViewer, and is still in the docstring as such.
>
> Should this simply removed from the docstring, or should this reference be restored? Make it a property?

We can remove it from the doc string

**Comment by nhthayer** [comment]
> I've just realized that we should add a test that checks that the keybindings update properly when the active layer changes, as we might be subject to a race condition here with our event system as viewer.events.active_layer triggers both the key_map_handler update and this dialog update - which now has to happen after the key_map_handler update!

You were correct, but it's not much of a race. It seems like the dialog's `update_active_layer` is always called before the keybindings have been updated. I've added a test that I think covers this situation (currently fails) and confirmed the unwanted behavior interacting with the UI. 

One potential fix could be to update the dialog (if it exists) everytime after the keymap handler is changed:
https://github.com/napari/napari/blob/42701623e9f21a7e37a4fe44d5e0dcdac1a66c6c/napari/_qt/qt_viewer.py#L314
```python 
    def _on_active_layer_change(self, event=None):
        """When active layer changes change keymap handler.

        Parameters
        ----------
        event : napari.utils.event.Event
            The napari event that triggered this method.
        """
        active_layer = self.viewer.active_layer

        if self._active_layer in self._key_map_handler.keymap_providers:
            self._key_map_handler.keymap_providers.remove(self._active_layer)

        if active_layer is not None:
            self._key_map_handler.keymap_providers.insert(0, active_layer)

        self._active_layer = active_layer
        # If a QtAboutKeyBindings exists, update its text for this layer
        dialog = self.findChild(QtAboutKeyBindings)
        if dialog is not None:
            dialog.update_active_layer()
```

Or is there another pattern that you would suggest to use to ensure that these operations occur in the correct order?

**Comment by sofroniewn** [comment]
> One potential fix could be to update the dialog (if it exists) everytime after the keymap handler is changed:

I like explicitly updating the dialog inside the `_on_active_layer_change`, that makes sense to me as it is where we update `_key_map_handler`. You can then disconnect the `active_layer` event connection from inside `QtAboutKeyBindings` which will be nice too.

I'm also good with the `dialog = self.findChild(QtAboutKeyBindings)`. We've tended to use explicit references to our Qt elements so, something like a `self._key_bindings_dialog` on the `QtViewer` which would start as `None` and then get set, but it's maybe a bit trickier for a dialog like this, so the `findChild` makes sense too.

File: napari/_qt/qt_viewer.py [hunk 1]
```diff
@@ -573,10 +574,15 @@ def toggle_console_visibility(self, event=None):
...
-        dialog.show()
+        if self._key_bindings_dialog is None:
+            self._key_bindings_dialog = QtAboutKeyBindings(
+                self.viewer, self._key_map_handler, parent=self
+            )
+        # make sure the dialog is shown
+        self._key_bindings_dialog.show()
+        # make sure the the dialog gets focus
+        self._key_bindings_dialog.raise_()  # for macOS
+        self._key_bindings_dialog.activateWindow()  # for Windows
```
Comment (nhthayer) [inline napari/_qt/qt_viewer.py]: > We've tended to use explicit references to our Qt elements so, something like a self._key_bindings_dialog on the QtViewer which would start as None and then get set. 

I like this better, as it made it obvious that there should only be one dialog window. I don't think being allowed to open a bunch of these windows really makes sense.

Comment (sofroniewn) [reply napari/_qt/qt_viewer.py]: nice, agreed!

**Comment by sofroniewn** [comment]
This is coming on really nicely @nhthayer! Is there anything else you want to do on it before review? If not I can mark it ready for review and give it some review

**Comment by nhthayer** [comment]
> Is there anything else you want to do on it before review?

I think that covers this issue. Obviously, there is a little more that could be covered in the tests, but as you said, it's better than nothing.

File: napari/_qt/dialogs/_tests/test_qt_about_key_bindings.py [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    assert key_bindings_dialog.viewer == viewer
+    assert key_bindings_dialog.key_map_handler == view._key_map_handler
+
+    # check ability to update the active layer, should've ran during init too
+    key_bindings_dialog.update_active_layer()
+
+    # check ability to change layer type selected in dropdown
+    for layer in key_bindings_dialog.key_bindings_strs.keys():
+        key_bindings_dialog.change_layer_type(layer)
+        # Could test to make sure text has been updated, but `toHtml` does not
```
Comment (sofroniewn) [inline napari/_qt/dialogs/_tests/test_qt_about_key_bindings.py:20]: Comment makes sense, I think it is fine to leave as is

File: napari/_qt/dialogs/_tests/test_qt_about_key_bindings.py [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    """Test creating dialog with method of qt_viewer."""
+    viewer = make_test_viewer()
+    view = viewer.window.qt_viewer
+    # check that dialog does not exist yet
+    assert not view.findChild(QtAboutKeyBindings)
+    # turn off showing the dialog for test
+    monkeypatch.setattr(QtAboutKeyBindings, 'show', lambda *a: None)
+    # create the dialog and make sure that it now exists
+    view.show_key_bindings_dialog()
+    assert isinstance(view.findChild(QtAboutKeyBindings), QtAboutKeyBindings)
```
Comment (sofroniewn) [inline napari/_qt/dialogs/_tests/test_qt_about_key_bindings.py:35]: Love it!

**Review by sofroniewn — APPROVED** [review]
Beautiful PR! Nice work!! I'm approving, will let sit over night in case anyone else has any additional feedback and will then merge.

We plan to be work on a way to make keybindings editable after we get persistent settings!!

**Review by jni — APPROVED** [review]
❤️ very very nice
