### PR TITLE
Fix `ShapeList.outline` validations for `int`/list like argument and add a test

### LINKED ISSUE #6212: Error when interacting with shapes: `TypeError: argument of type 'numpy.int32' is not iterable`
## To Reproduce

1. Create a shape layer
2. Create a shape
3. Use either the `Selecte vertices` or `Select shapes` modes

- Traceback:

<details>

```python-traceback
TypeError                                 Traceback (most recent call last)
~\anaconda3\envs\napari-dev\lib\site-packages\vispy\app\backends\_qt.py in paintGL(self=<vispy.app.backends._qt.CanvasBackendDesktop object>)
    901         # (0, 0, self.width(), self.height()))
    902         self._vispy_canvas.set_current()
--> 903         self._vispy_canvas.events.draw(region=None)
        self._vispy_canvas.events.draw = <vispy.util.event.EventEmitter object at 0x000002482CD5CDC0>
        global region = undefined
    904
    905         # Clear the alpha channel with QOpenGLWidget (Qt >= 5.4), otherwise the

~\anaconda3\envs\napari-dev\lib\site-packages\vispy\util\event.py in __call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'region': None})
    451                     raise RuntimeError('EventEmitter loop detected!')
    452
--> 453                 self._invoke_callback(cb, event)
        self._invoke_callback = <bound method EventEmitter._invoke_callback of <vispy.util.event.EventEmitter object at 0x000002482CD5CDC0>>
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x000002482CD4A410>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    454                 if event.blocked:
    455                     break

~\anaconda3\envs\napari-dev\lib\site-packages\vispy\util\event.py in _invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    469             cb(event)
    470         except Exception:
--> 471             _handle_exception(self.ignore_callback_errors,
        global _handle_exception = <function _handle_exception at 0x00000248224A3E20>
        self.ignore_callback_errors = False
        self.print_callback_errors = 'reminders'
        self = <vispy.util.event.EventEmitter object at 0x000002482CD5CDC0>
        global cb_event = undefined
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x000002482CD4A410>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    472                               self.print_callback_errors,
    473                               self, cb_event=(cb, event))

~\anaconda3\envs\napari-dev\lib\site-packages\vispy\util\event.py in _invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    467     def _invoke_callback(self, cb, event):
    468         try:
--> 469             cb(event)
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x000002482CD4A410>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    470         except Exception:
    471             _handle_exception(self.ignore_callback_errors,

E:\Acer\Documentos\Quansight\Napari\napari\napari\_vispy\canvas.py in on_draw(self=<napari._vispy.canvas.VispyCanvas object>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    527             else:
    528                 displayed_axes = list(self.viewer.dims.displayed[-nd:])
--> 529             layer._update_draw(
        layer._update_draw = <bound method Shapes._update_draw of <Shapes layer 'Shapes' at 0x2483a032f80>>
        global scale_factor = undefined
        self.viewer.camera.zoom = 0.6784840624999999
        global corner_pixels_displayed = undefined
        canvas_corners_world = <class 'numpy.ndarray'> (2, 2) float64
        displayed_axes = [0, 1]
        global shape_threshold = undefined
        self._scene_canvas.size = (499, 528)
    530                 scale_factor=1 / self.viewer.camera.zoom,
    531                 corner_pixels_displayed=canvas_corners_world[

E:\Acer\Documentos\Quansight\Napari\napari\napari\layers\shapes\shapes.py in _update_draw(self=<Shapes layer 'Shapes'>, scale_factor=1.4738739718001852, corner_pixels_displayed=<class 'numpy.ndarray'> (2, 2) float64, shape_threshold=(499, 528))
   2731             scale_factor, corner_pixels_displayed, shape_threshold
   2732         )
-> 2733         self._set_highlight(force=True)
        self._set_highlight = <bound method Shapes._set_highlight of <Shapes layer 'Shapes' at 0x2483a032f80>>
        global force = undefined
   2734
   2735     def _get_value(self, position):

E:\Acer\Documentos\Quansight\Napari\napari\napari\layers\shapes\shapes.py in _set_highlight(self=<Shapes layer 'Shapes'>, force=True)
   2539         self._value_stored = copy(self._value)
   2540         self._drag_box_stored = copy(self._drag_box)
-> 2541         self.events.highlight()
        self.events.highlight = <napari.utils.events.event.EventEmitter object at 0x000002483A05D420>
   2542
   2543     def _finish_drawing(self, event=None):

E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\events\event.py in __call__(self=<napari.utils.events.event.EventEmitter object>, *args=(), **kwargs={})
    761                     continue
    762
--> 763                 self._invoke_callback(cb, event if pass_event else None)
        self._invoke_callback = <bound method EventEmitter._invoke_callback of <napari.utils.events.event.EventEmitter object at 0x000002483A05D420>>
        cb = <bound method VispyShapesLayer._on_highlight_change of <napari._vispy.layers.shapes.VispyShapesLayer object at 0x000002483A05E290>>
        event = <Event blocked=False handled=False native=None source=None sources=[] type='highlight'>
        pass_event = False
    764                 if event.blocked:
    765                     break

E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\events\event.py in _invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<bound method VispyShapesLayer._on_highlight_cha...ri._vispy.layers.shapes.VispyShapesLayer object>>, event=None)
    799                 self.disconnect(cb)
    800                 return
--> 801             _handle_exception(
        global _handle_exception = <function _handle_exception at 0x00000248224A3E20>
        self.ignore_callback_errors = False
        self.print_callback_errors = 'reminders'
        self = <napari.utils.events.event.EventEmitter object at 0x000002483A05D420>
        global cb_event = undefined
        cb = <bound method VispyShapesLayer._on_highlight_change of <napari._vispy.layers.shapes.VispyShapesLayer object at 0x000002483A05E290>>
        event = None
    802                 self.ignore_callback_errors,
    803                 self.print_callback_errors,

E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\events\event.py in _invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<bound method VispyShapesLayer._on_highlight_cha...ri._vispy.layers.shapes.VispyShapesLayer object>>, event=None)
    788                 cb(event)
    789             else:
--> 790                 cb()
        cb = <bound method VispyShapesLayer._on_highlight_change of <napari._vispy.layers.shapes.VispyShapesLayer object at 0x000002483A05E290>>
    791         except Exception as e:  # noqa: BLE001
    792             # dead Qt object with living python pointer. not importing Qt

E:\Acer\Documentos\Quansight\Napari\napari\napari\_vispy\layers\shapes.py in _on_highlight_change(self=<napari._vispy.layers.shapes.VispyShapesLayer object>)
     63
     64         # Compute the vertices and faces of any shape outlines
---> 65         vertices, faces = self.layer._outline_shapes()
        vertices = undefined
        faces = undefined
        self.layer._outline_shapes = <bound method Shapes._outline_shapes of <Shapes layer 'Shapes' at 0x2483a032f80>>
     66
     67         if vertices is None or len(vertices) == 0 or len(faces) == 0:

E:\Acer\Documentos\Quansight\Napari\napari\napari\layers\shapes\shapes.py in _outline_shapes(self=<Shapes layer 'Shapes'>)
   2418                 index = self._value[0]
   2419
-> 2420             centers, offsets, triangles = self._data_view.outline(index)
        centers = undefined
        offsets = undefined
        triangles = undefined
        self._data_view.outline = <bound method ShapeList.outline of <napari.layers.shapes._shape_list.ShapeList object at 0x000002483A05D870>>
        index = 0
   2421             vertices = centers + (
   2422                 self._normalized_scale_factor * self._highlight_width * offsets

E:\Acer\Documentos\Quansight\Napari\napari\napari\layers\shapes\_shape_list.py in outline(self=<napari.layers.shapes._shape_list.ShapeList object>, indices=0)
    963         else:
    964             meshes = self._mesh.triangles_index
--> 965             triangle_indices = [
        triangle_indices = undefined
        i = undefined
        global x = undefined
        global enumerate = undefined
        meshes = <class 'numpy.ndarray'> (10, 2) int32
        indices = 0
    966                 i
    967                 for i, x in enumerate(meshes)

E:\Acer\Documentos\Quansight\Napari\napari\napari\layers\shapes\_shape_list.py in <listcomp>(.0=<enumerate object>)
    966                 i
    967                 for i, x in enumerate(meshes)
--> 968                 if x[0] in indices and x[1] == 1
        x = <class 'numpy.ndarray'> (2,) int32
        global indices = undefined
    969             ]
    970             meshes = self._mesh.vertices_index

TypeError: argument of type 'numpy.int32' is not iterable

```

</details>

- Preview:

shapes

## Expected behavior

No error should happen

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

<details>

```
napari: 0.5.0a2.dev318+ge7ef9393
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.3
SciPy: 1.9.3
Dask: 2022.10.2
VisPy: 0.13.0
magicgui: 0.6.0
superqt: 0.5.3
in-n-out: 0.1.5
app-model: 0.1.4
npe2: 0.7.2

OpenGL:
- GL version: 4.5.0 - Build 25.20.100.6444
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1366x768, scale 1.0
- screen 2: resolution 1600x900, scale 1.0

Settings path:
- C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml

```

</details>

Happens to me running from main at e7ef9393b but seems like removing that commit (I think is a pre-commit one) prevents the error to appear 🤔

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

Closes #6212 

# Description

* Improve `isinstance` validations for `int` and list like `indices` argument using `Sequence` instead of `int` on the `ShapeList.outline` method.
* Add a test checking the usage of the method passing `int` and a `np.array` variables as argument

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Marking this 0.5.0 since the PR that introduced the bug is also 0.5.0

File: napari/layers/shapes/_tests/test_shape_list.py [hunk 1]
```diff
@@ -23,6 +23,27 @@ def test_adding_to_shape_list():
...
+    data = 20 * np.random.random((4, 2))
+    shape = Rectangle(data)
+    shape_list = ShapeList()
+
+    shape_list.add(shape)
+
+    outline_by_index = shape_list.outline(0)
+    assert isinstance(outline_by_index, tuple)
+
+    outline_by_index_list = shape_list.outline(np.array(0))
```
Comment (psobolewskiPhD) [inline napari/layers/shapes/_tests/test_shape_list.py]: To test both branches, does it make sense to also add something of type Sequence? like `[0]`

File: napari/layers/shapes/_shape_list.py [hunk 2]
```diff
@@ -951,7 +951,7 @@ def outline(self, indices: Union[int, Sequence[int]]):
         triangles : np.ndarray
             Mx3 array of any indices of vertices for triangles of outline
         """
-        if isinstance(indices, int):
```
Comment (Carreau) [inline napari/layers/shapes/_shape_list.py:954]: I'm guessing there might be a perf reason, 
but can't we:
```python
if not isinstance(indices, Sequence):
   indices = [indices]
```

and then have a branch less function ?

Comment (dalthviz) [reply napari/layers/shapes/_shape_list.py:954]: That makes sense to me :+1: but what do you think @psobolewskiPhD @Czaki ?

Also, that would mean to change the current method definition to be something like:

```python
    def outline(self, indices: Union[int, Sequence[int]]):
        """Finds outlines of shapes listed in indices

        Parameters
        ----------
        indices : int | list
            Location in list of the shapes to be outline. If list must be a
            list of int

        Returns
        -------
        centers : np.ndarray
            Nx2 array of centers of outline
        offsets : np.ndarray
            Nx2 array of offsets of outline
        triangles : np.ndarray
            Mx3 array of any indices of vertices for triangles of outline
        """
        if not isinstance(indices, Sequence):
            indices = [indices]
        meshes = self._mesh.triangles_index
        triangle_indices = [
            i
            for i, x in enumerate(meshes)
            if x[0] in indices and x[1] == 1
        ]
        meshes = self._mesh.vertices_index
        vertices_indices = [
            i
            for i, x in enumerate(meshes)
            if x[0] in indices and x[1] == 1
        ]

        offsets = self._mesh.vertices_offsets[vertices_indices]
        centers = self._mesh.vertices_centers[vertices_indices]
        triangles = self._mesh.triangles[triangle_indices]

        t_ind = self._mesh.triangles_index[triangle_indices][:, 0]
        inds = self._mesh.vertices_index[vertices_indices][:, 0]
        starts = np.unique(inds, return_index=True)[1]
        for i, ind in enumerate(indices):
            inds = t_ind == ind
            adjust_index = starts[i] - vertices_indices[starts[i]]
            triangles[inds] = triangles[inds] + adjust_index

        return centers, offsets, triangles

```
?

And thank you for the feedback @Carreau !

Comment (psobolewskiPhD) [reply napari/layers/shapes/_shape_list.py:954]: Certainly makes it simpler and easier to follow...

Comment (Carreau) [reply napari/layers/shapes/_shape_list.py:954]: I would even go one step further, introduce `def outlines(self,...)` that only take sequences, and have `def outline` with the only the `if not sequence...`. 

The reason being that `outline()` seem to be use in a single place, in a private function lower down the file, and from coverage report, it's not even clean the case where `indices` is an int is used.

We obviously can't remove it as it's public, but having a type stable method would be useful internally.

Comment (dalthviz) [reply napari/layers/shapes/_shape_list.py:954]: Just to be sure, you mean doing something like:

```python
    def outline(self, indices: Union[int, Sequence[int]]):
        """Finds outlines of shapes listed in indices

        Parameters
        ----------
        indices : int | list
            Location in list of the shapes to be outline. If list must be a
            list of int

        Returns
        -------
        centers : np.ndarray
            Nx2 array of centers of outline
        offsets : np.ndarray
            Nx2 array of offsets of outline
        triangles : np.ndarray
            Mx3 array of any indices of vertices for triangles of outline
        """
        if not isinstance(indices, Sequence):
            indices = [indices]
        return self.outlines(indices)

    def outlines(self, indices: Sequence[int]):
        """Finds outlines of shapes listed in indices

        Parameters
        ----------
        indices : Sequence[int]
            Location in list of the shapes to be outline.

        Returns
        -------
        centers : np.ndarray
            Nx2 array of centers of outline
        offsets : np.ndarray
            Nx2 array of offsets of outline
        triangles : np.ndarray
            Mx3 array of any indices of vertices for triangles of outline
        """
        meshes = self._mesh.triangles_index
        triangle_indices = [
            i
            for i, x in enumerate(meshes)
            if x[0] in indices and x[1] == 1
        ]
        meshes = self._mesh.vertices_index
        vertices_indices = [
            i
            for i, x in enumerate(meshes)
            if x[0] in indices and x[1] == 1
        ]

        offsets = self._mesh.vertices_offsets[vertices_indices]
        centers = self._mesh.vertices_centers[vertices_indices]
        triangles = self._mesh.triangles[triangle_indices]

        t_ind = self._mesh.triangles_index[triangle_indices][:, 0]
        inds = self._mesh.vertices_index[vertices_indices][:, 0]
        starts = np.unique(inds, return_index=True)[1]
        for i, ind in enumerate(indices):
            inds = t_ind == ind
            adjust_index = starts[i] - vertices_indices[starts[i]]
            triangles[inds] = triangles[inds] + adjust_index

        return centers, offsets, triangles
```
right?

Comment (dalthviz) [reply napari/layers/shapes/_shape_list.py:954]: Pushed a commit with the initial suggestion (a branchless function), but let me know what do you think about defining a a new method that accepts only `Sequence`

Comment (Carreau) [reply napari/layers/shapes/_shape_list.py:954]: > Just to be sure, you mean doing something like:
> 
> ```python
>     def outline(self, indices: Union[int, Sequence[int]]):
>         """Finds outlines of shapes listed in indices
> 
>         Parameters
>         ----------
>         indices : int | list
>             Location in list of the shapes to be outline. If list must be a
>             list of int
> 
>         Returns
>         -------
>         centers : np.ndarray
>             Nx2 array of centers of outline
>         offsets : np.ndarray
>             Nx2 array of offsets of outline
>         triangles : np.ndarray
>             Mx3 array of any indices of vertices for triangles of outline
>         """
>         if not isinstance(indices, Sequence):
>             indices = [indices]
>         return self.outlines(indices)
> 
>     def outlines(self, indices: Sequence[int]):
>         """Finds outlines of shapes listed in indices
> 
>         Parameters
>         ----------
>         indices : Sequence[int]
>             Location in list of the shapes to be outline.
> 
>         Returns
>         -------
>         centers : np.ndarray
>             Nx2 array of centers of outline
>         offsets : np.ndarray
>             Nx2 array of offsets of outline
>         triangles : np.ndarray
>             Mx3 array of any indices of vertices for triangles of outline
>         """
>         meshes = self._mesh.triangles_index
>         triangle_indices = [
>             i
>             for i, x in enumerate(meshes)
>             if x[0] in indices and x[1] == 1
>         ]
>         meshes = self._mesh.vertices_index
>         vertices_indices = [
>             i
>             for i, x in enumerate(meshes)
>             if x[0] in indices and x[1] == 1
>         ]
> 
>         offsets = self._mesh.vertices_offsets[vertices_indices]
>         centers = self._mesh.vertices_centers[vertices_indices]
>         triangles = self._mesh.triangles[triangle_indices]
> 
>         t_ind = self._mesh.triangles_index[triangle_indices][:, 0]
>         inds = self._mesh.vertices_index[vertices_indices][:, 0]
>         starts = np.unique(inds, return_index=True)[1]
>         for i, ind in enumerate(indices):
>             inds = t_ind == ind
>             adjust_index = starts[i] - vertices_indices[starts[i]]
>             triangles[inds] = triangles[inds] + adjust_index
> 
>         return centers, offsets, triangles
> ```
> 
> right?

Yes that's what I meant, sorry I was at NF summit and not super active.

Comment (Carreau) [reply napari/layers/shapes/_shape_list.py:954]: And It's just a suggestion, core devs would have to pitch in/validate.

**Review by Carreau — APPROVED** [review]

**Comment by dalthviz** [comment]
Note: After updating the branch with the latest base/main a typing error appeared ([`napari/components/_viewer_key_bindings.py:168: error: Item "None" of "Any | None" has no attribute "_list"  [union-attr]`](https://github.com/napari/napari/actions/runs/6224977847/job/16894393020#step:5:16)). Last commit fixes that but maybe the change should be done in its own PR?

**Comment by melonora** [comment]
@Czaki I think we should change the milestone here as the error that is fixed by this PR also occurs when just panning and zooming with a shapes layer open and thus is quite critical. What do you think?

**Comment by Czaki** [comment]
@melonora but @psobolewskiPhD claims that pr that introduces it is 0.5.0. Did you check that bug exists in 0.4.18?

**Comment by melonora** [comment]
> @melonora but @psobolewskiPhD claims that pr that introduces it is 0.5.0. Did you check that bug exists in 0.4.18?

@Czaki @psobolewskiPhD is correct, sorry my bad I thought I was working with version 0.4.18 when testing.

File: napari/layers/shapes/_shape_list.py [hunk 3]
```diff
@@ -951,43 +951,28 @@ def outline(self, indices: Union[int, Sequence[int]]):
...
+        if not isinstance(indices, Sequence):
+            indices = [indices]
+        meshes = self._mesh.triangles_index
+        triangle_indices = [
+            i for i, x in enumerate(meshes) if x[0] in indices and x[1] == 1
+        ]
+        meshes = self._mesh.vertices_index
+        vertices_indices = [
+            i for i, x in enumerate(meshes) if x[0] in indices and x[1] == 1
+        ]
```
Comment (Czaki) [inline napari/layers/shapes/_shape_list.py]: As we refactor this code. Here we have iteration to check if the item is present in the list. 

It may produce big penalties for performance on layers with a large number of elements. As docstring suggests that it is a list of ints then creating `indices_set = set(indices)` and using it should be easy.

File: napari/layers/shapes/_shape_list.py (hunk 2 above)
Comment (Czaki) [reply napari/layers/shapes/_shape_list.py:954]: The @Carreau suggestion looks good and provides a cleaner interface.

**Review by Czaki — COMMENTED** [review]
I like this PR. I think that it could be a little improvement based on @Carreau suggestions and lookup in a set instead of a list.

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
Could someone check if the original bug is present in 0.4.18?

**Comment by psobolewskiPhD** [comment]
> Could someone check if the original bug is present in 0.4.18?

0.4.18 is fine--I double checked--the bug was introduced in `main` by
https://github.com/napari/napari/pull/6128

**Comment by Carreau** [comment]
This got the "Ready-to-merge" label 2 days ago and got no objections. Merging to move the queue forward. 

Thanks.
