### PR TITLE
Provide default colors automatically in DirectLabelsColormap

### LINKED ISSUE #109: Labels layers don't load with napari 0.5.0 (dev)
In 0.4.19 there were a number of deprecations to labels kwargs:
https://github.com/napari/napari/pull/6542
In 0.5.0 they are removed:
https://github.com/napari/napari/pull/6641

This results in a traceback when trying to load ome zarr with labels, e.g.
`NAPARI_ASYNC=1 napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0`
validator: https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0/

```
Traceback (most recent call last):
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1474, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: add_labels() got an unexpected keyword argument 'color'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1283, in _open_or_raise_error
    added = self._add_layers_with_plugins(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1401, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1479, in _add_layer_from_data
    raise TypeError(
TypeError: _add_layer_from_data received an unexpected keyword argument ('color') for layer type labels
```

Env details:
napari 0.5.0 from main 5c1e7281bbc11878a748add1006f7211473be16b
0.5.2 of this plugin
0.8.3 of ome-zarr
python 3.11.7
macOS arm64

### PR DESCRIPTION
**Pull request by jni**
While trying to fix ome/napari-ome-zarr#109 on the ome side after #7025, I found that I was still getting errors — now by the color_dict validator, which requires a None key or a defaultdict. Ultimately, I think this is a quirky interface that I don't think we should impose on ome-zarr or their readers. Therefore, I've changed the ValueError to a warning. I'd consider removing the warning altogether.

### CODE REVIEW

**Review by brisvag — COMMENTED** [review]
I like it like this. Was there a reason why @Czaki didn't like it?

**Comment by Czaki** [comment]
The original behavior was to set `None` and `background_color` in `Labels.color` setter. The whole logic was removed 

https://github.com/napari/napari/blob/bd47bf0ecbfc74f1efa82343dbdfcbefd3f0bded/napari/layers/labels/labels.py#L647-L650

As I checked, it was introduced in #6542. I do not find comment with explanation (but it is long PR and I do not read it all). 

But if this PR is restoring logic from `Labels.color`, Then it should be `"black"`, not `"transparent"`

**Comment by jni** [comment]
Sorry if I misremembered — so do we want to keep the warning or have things Just Work? (Or Not Work, depending on whether you expect this behaviour 😂)

**Comment by jni** [comment]
(Updated the original comment)

**Comment by brisvag** [comment]
I don't think we need to restore behaviour from then, just make sure it doesn't error out if it doesn't need to. Transparent seems like a good default to me. I would leave the warning, because I think it might be common to forget a key in the dict, and it would be confuding to debug why you don't see some labels. The warning is easy to suppress by being explicit.

**Comment by Czaki** [comment]
I do not have a strong opinion here. 

`black` has this advantage, that in many scenarios you see that something is there, but the color is the same as the background of the default theme. 

But it could be transparent also. 

The warning seems good.

**Review by Czaki — APPROVED** [review]

**Review by brisvag — APPROVED** [review]

**Comment by jni** [comment]
Ok I will merge this and then make a separate PR to update the default colour, and we can discuss there whether we prefer transparent or translucent-black. I do kinda like translucent black indeed.
