### ISSUE TITLE
[Settings] Main: toggling Dask cache results in a traceback

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7020]
### 🐛 Bug Report

In the Settings > Application, toggling the Dask cache Enabled checkbox results in a traceback:
`AttributeError: 'DaskSettings' object has no attribute 'items'`
<details>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py:134, in CheckboxSchemaWidget.configure.<locals>.<lambda>(_=0)
    133 def configure(self):
--> 134     self.stateChanged.connect(lambda _: self.on_changed.emit(self.state))
        self = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.CheckboxSchemaWidget object at 0x16510ead0>
    135     self.opacity = QtWidgets.QGraphicsOpacityEffect(self)
    136     self.setGraphicsEffect(self.opacity)

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/signal.py:22, in BoundSignal.emit(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.signal.BoundSignal object>, *args=(False,))
     20 def emit(self, *args):
     21     for sub in self._subscribers:
---> 22         sub(*args)
        sub = functools.partial(<bound method ObjectSchemaWidgetMinix.widget_on_changed of <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object at 0x16510ed50>>, 'enabled')
        args = (False,)

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py:710, in ObjectSchemaWidgetMinix.widget_on_changed(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object>, name='enabled', value=False)
    708 def widget_on_changed(self, name: str, value):
    709     self.state[name] = value
--> 710     self.on_changed.emit(self.state)
        self = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object at 0x16510ed50>

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/signal.py:22, in BoundSignal.emit(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.signal.BoundSignal object>, *args=({'cache': 4.29, 'enabled': False},))
     20 def emit(self, *args):
     21     for sub in self._subscribers:
---> 22         sub(*args)
        sub = functools.partial(<bound method ObjectSchemaWidgetMinix.widget_on_changed of <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object at 0x1651031b0>>, 'dask')
        args = ({'enabled': False, 'cache': 4.29},)

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py:710, in ObjectSchemaWidgetMinix.widget_on_changed(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object>, name='dask', value={'cache': 4.29, 'enabled': False})
    708 def widget_on_changed(self, name: str, value):
    709     self.state[name] = value
--> 710     self.on_changed.emit(self.state)
        self = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object at 0x1651031b0>

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/signal.py:22, in BoundSignal.emit(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.signal.BoundSignal object>, *args=({'brush_size_on_mouse_move_modifiers': 'Alt', 'confirm_close_window': True, 'console_notification_level': 'none', 'dask': {'cache': 4.29, 'enabled': False}, 'grid_height': -1, 'grid_stride': 1, 'grid_width': -1, 'gui_notification_level': 'info', 'hold_button_delay': 0.5, 'language': 'en', ...},))
     20 def emit(self, *args):
     21     for sub in self._subscribers:
---> 22         sub(*args)
        sub = <function PreferencesDialog._add_page.<locals>.<lambda> at 0x16510df80>
        args = ({'language': 'en', 'save_window_geometry': True, 'save_window_state': False, 'gui_notification_level': 'info', 'console_notification_level': 'none', 'playback_fps': 10, 'playback_mode': 'loop', 'grid_stride': 1, 'grid_width': -1, 'grid_height': -1, 'confirm_close_window': True, 'hold_button_delay': 0.5, 'brush_size_on_mouse_move_modifiers': 'Alt', 'dask': {'enabled': False, 'cache': 4.29}, 'new_labels_dtype': 'uint8'},)

File ~/Dev/napari/napari/_qt/dialogs/preferences_dialog.py:130, in PreferencesDialog._add_page.<locals>.<lambda>(d={'brush_size_on_mouse_move_modifiers': 'Alt', 'confirm_close_window': True, 'console_notification_level': 'none', 'dask': {'cache': 4.29, 'enabled': False}, 'grid_height': -1, 'grid_stride': 1, 'grid_width': -1, 'gui_notification_level': 'info', 'hold_button_delay': 0.5, 'language': 'en', ...})
    127 form.widget.state = values
    128 # make settings follow state of the form widget
    129 form.widget.on_changed.connect(
--> 130     lambda d: getattr(self._settings, name.lower()).update(d)
        name = 'Application'
        self._settings = NapariSettings (defaults excluded)
----------------------------------
application:
  first_time: false
  window_position:
  - 77
  - 25
  window_size:
  - 1397
  - 890
  preferences_size:
  - 1065
  - 846
  save_history:
  - /Users/piotrsobolewski/Downloads/test-all-layers
  dask:
    enabled: false
    cache: 4.29
appearance:
  highlight:
    highlight_thickness: 4
plugins:
  use_npe2_adaptor: true
  disabled_plugins:
  - napari-svg
experimental:
  async_: true

        self = <napari._qt.dialogs.preferences_dialog.PreferencesDialog object at 0x165102530>
        d = {'language': 'en', 'save_window_geometry': True, 'save_window_state': False, 'gui_notification_level': 'info', 'console_notification_level': 'none', 'playback_fps': 10, 'playback_mode': 'loop', 'grid_stride': 1, 'grid_width': -1, 'grid_height': -1, 'confirm_close_window': True, 'hold_button_delay': 0.5, 'brush_size_on_mouse_move_modifiers': 'Alt', 'dask': {'enabled': False, 'cache': 4.29}, 'new_labels_dtype': 'uint8'}
    131 )
    132 # make widgets follow values of the settings
    133 settings_category = getattr(self._settings, name.lower())

File ~/Dev/napari/napari/utils/events/evented_model.py:451, in EventedModel.update(self=ApplicationSettings(first_time=False, ipy_intera...), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>), values={'brush_size_on_mouse_move_modifiers': 'Alt', 'confirm_close_window': True, 'console_notification_level': 'none', 'dask': {'cache': 4.29, 'enabled': False}, 'grid_height': -1, 'grid_stride': 1, 'grid_width': -1, 'gui_notification_level': 'info', 'hold_button_delay': 0.5, 'language': 'en', ...}, recurse=True)
    449 field = getattr(self, key)
    450 if isinstance(field, EventedModel) and recurse:
--> 451     field.update(value, recurse=recurse)
        value = {'enabled': False, 'cache': 4.29}
        field = DaskSettings(enabled=False, cache=4.29)
        recurse = True
    452 else:
    453     setattr(self, key, value)

File ~/Dev/napari/napari/utils/events/evented_model.py:456, in EventedModel.update(self=DaskSettings(enabled=False, cache=4.29), values={'cache': 4.29, 'enabled': False}, recurse=True)
    453             setattr(self, key, value)
    455 if block.count:
--> 456     self.events(Event(self))
        self = DaskSettings(enabled=False, cache=4.29)

File ~/Dev/napari/napari/utils/events/event.py:764, in EventEmitter.__call__(self=<napari.utils.events.event.EmitterGroup object>, *args=(<Event blocked=False handled=False native=None s...=[] type=DaskSettings(enabled=False, cache=4.29)>,), **kwargs={})
    761     self._block_counter.update([cb])
    762     continue
--> 764 self._invoke_callback(cb, event if pass_event else None)
        event = <Event blocked=False handled=False native=None source=None sources=[] type=DaskSettings(enabled=False, cache=4.29)>
        self = <napari.utils.events.event.EmitterGroup object at 0x15d67ab10>
        cb = <bound method ApplicationSettings._dask_changed of ApplicationSettings(first_time=False, ipy_interactive=True, language='en', save_window_geometry=True, save_window_state=False, window_position=(77, 25), window_size=(1397, 890), window_maximized=False, window_fullscreen=False, window_state=None, window_statusbar=True, preferences_size=(1065, 846), gui_notification_level=<NotificationSeverity.INFO: 'info'>, console_notification_level=<NotificationSeverity.NONE: 'none'>, open_history=[], save_history=['/Users/piotrsobolewski/Downloads/test-all-layers'], playback_fps=10, playback_mode=<LoopMode.LOOP: 'loop'>, grid_stride=1, grid_width=-1, grid_height=-1, confirm_close_window=True, hold_button_delay=0.5, brush_size_on_mouse_move_modifiers=<BrushSizeOnMouseModifiers.ALT: 'Alt'>, dask=DaskSettings(enabled=False, cache=4.29), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>
        pass_event = False
    765 if event.blocked:
    766     break

File ~/Dev/napari/napari/utils/events/event.py:802, in EventEmitter._invoke_callback(self=<napari.utils.events.event.EmitterGroup object>, cb=<bound method ApplicationSettings._dask_changed ..., new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>, event=None)
    800     self.disconnect(cb)
    801     return
--> 802 _handle_exception(
        self = <napari.utils.events.event.EmitterGroup object at 0x15d67ab10>
        event = None
        cb = <bound method ApplicationSettings._dask_changed of ApplicationSettings(first_time=False, ipy_interactive=True, language='en', save_window_geometry=True, save_window_state=False, window_position=(77, 25), window_size=(1397, 890), window_maximized=False, window_fullscreen=False, window_state=None, window_statusbar=True, preferences_size=(1065, 846), gui_notification_level=<NotificationSeverity.INFO: 'info'>, console_notification_level=<NotificationSeverity.NONE: 'none'>, open_history=[], save_history=['/Users/piotrsobolewski/Downloads/test-all-layers'], playback_fps=10, playback_mode=<LoopMode.LOOP: 'loop'>, grid_stride=1, grid_width=-1, grid_height=-1, confirm_close_window=True, hold_button_delay=0.5, brush_size_on_mouse_move_modifiers=<BrushSizeOnMouseModifiers.ALT: 'Alt'>, dask=DaskSettings(enabled=False, cache=4.29), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>
        (cb, event) = (<bound method ApplicationSettings._dask_changed of ApplicationSettings(first_time=False, ipy_interactive=True, language='en', save_window_geometry=True, save_window_state=False, window_position=(77, 25), window_size=(1397, 890), window_maximized=False, window_fullscreen=False, window_state=None, window_statusbar=True, preferences_size=(1065, 846), gui_notification_level=<NotificationSeverity.INFO: 'info'>, console_notification_level=<NotificationSeverity.NONE: 'none'>, open_history=[], save_history=['/Users/piotrsobolewski/Downloads/test-all-layers'], playback_fps=10, playback_mode=<LoopMode.LOOP: 'loop'>, grid_stride=1, grid_width=-1, grid_height=-1, confirm_close_window=True, hold_button_delay=0.5, brush_size_on_mouse_move_modifiers=<BrushSizeOnMouseModifiers.ALT: 'Alt'>, dask=DaskSettings(enabled=False, cache=4.29), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>, None)
    803     self.ignore_callback_errors,
    804     self.print_callback_errors,
    805     self,
    806     cb_event=(cb, event),
    807 )

File ~/Dev/napari/napari/utils/events/event.py:791, in EventEmitter._invoke_callback(self=<napari.utils.events.event.EmitterGroup object>, cb=<bound method ApplicationSettings._dask_changed ..., new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>, event=None)
    789         cb(event)
    790     else:
--> 791         cb()
        cb = <bound method ApplicationSettings._dask_changed of ApplicationSettings(first_time=False, ipy_interactive=True, language='en', save_window_geometry=True, save_window_state=False, window_position=(77, 25), window_size=(1397, 890), window_maximized=False, window_fullscreen=False, window_state=None, window_statusbar=True, preferences_size=(1065, 846), gui_notification_level=<NotificationSeverity.INFO: 'info'>, console_notification_level=<NotificationSeverity.NONE: 'none'>, open_history=[], save_history=['/Users/piotrsobolewski/Downloads/test-all-layers'], playback_fps=10, playback_mode=<LoopMode.LOOP: 'loop'>, grid_stride=1, grid_width=-1, grid_height=-1, confirm_close_window=True, hold_button_delay=0.5, brush_size_on_mouse_move_modifiers=<BrushSizeOnMouseModifiers.ALT: 'Alt'>, dask=DaskSettings(enabled=False, cache=4.29), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)>
    792 except Exception as e:  # noqa: BLE001
    793     # dead Qt object with living python pointer. not importing Qt
    794     # here... but this error is consistent across backends
    795     if (
    796         isinstance(e, RuntimeError)
    797         and 'C++' in str(e)
    798         and str(e).endswith(('has been deleted', 'already deleted.'))
    799     ):

File ~/Dev/napari/napari/settings/_application.py:44, in ApplicationSettings._dask_changed(self=ApplicationSettings(first_time=False, ipy_intera...), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>))
     43 def _dask_changed(self) -> None:
---> 44     self.events.dask(value=self.dask)
        self.dask = DaskSettings(enabled=False, cache=4.29)
        self = ApplicationSettings(first_time=False, ipy_interactive=True, language='en', save_window_geometry=True, save_window_state=False, window_position=(77, 25), window_size=(1397, 890), window_maximized=False, window_fullscreen=False, window_state=None, window_statusbar=True, preferences_size=(1065, 846), gui_notification_level=<NotificationSeverity.INFO: 'info'>, console_notification_level=<NotificationSeverity.NONE: 'none'>, open_history=[], save_history=['/Users/piotrsobolewski/Downloads/test-all-layers'], playback_fps=10, playback_mode=<LoopMode.LOOP: 'loop'>, grid_stride=1, grid_width=-1, grid_height=-1, confirm_close_window=True, hold_button_delay=0.5, brush_size_on_mouse_move_modifiers=<BrushSizeOnMouseModifiers.ALT: 'Alt'>, dask=DaskSettings(enabled=False, cache=4.29), new_labels_dtype=<LabelDTypes.uint8: 'uint8'>)

File ~/Dev/napari/napari/utils/events/event.py:764, in EventEmitter.__call__(self=<napari.utils.events.event.EventEmitter object>, *args=(), **kwargs={'value': DaskSettings(enabled=False, cache=4.29)})
    761     self._block_counter.update([cb])
    762     continue
--> 764 self._invoke_callback(cb, event if pass_event else None)
        event = <Event blocked=False handled=False native=None source=None sources=[] type='dask'>
        self = <napari.utils.events.event.EventEmitter object at 0x15d64a960>
        cb = <function update_widget_state.<locals>._update_widget_state at 0x165296a20>
        pass_event = True
    765 if event.blocked:
    766     break

File ~/Dev/napari/napari/utils/events/event.py:802, in EventEmitter._invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<function update_widget_state.<locals>._update_widget_state>, event=<Event blocked=False handled=False native=None source=None sources=[] type='dask'>)
    800     self.disconnect(cb)
    801     return
--> 802 _handle_exception(
        self = <napari.utils.events.event.EventEmitter object at 0x15d64a960>
        event = <Event blocked=False handled=False native=None source=None sources=[] type='dask'>
        cb = <function update_widget_state.<locals>._update_widget_state at 0x165296a20>
        (cb, event) = (<function update_widget_state.<locals>._update_widget_state at 0x165296a20>, <Event blocked=False handled=False native=None source=None sources=[] type='dask'>)
    803     self.ignore_callback_errors,
    804     self.print_callback_errors,
    805     self,
    806     cb_event=(cb, event),
    807 )

File ~/Dev/napari/napari/utils/events/event.py:789, in EventEmitter._invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<function update_widget_state.<locals>._update_widget_state>, event=<Event blocked=False handled=False native=None source=None sources=[] type='dask'>)
    787 try:
    788     if event is not None:
--> 789         cb(event)
        event = <Event blocked=False handled=False native=None source=None sources=[] type='dask'>
        cb = <function update_widget_state.<locals>._update_widget_state at 0x165296a20>
    790     else:
    791         cb()

File ~/Dev/napari/napari/_qt/dialogs/preferences_dialog.py:263, in update_widget_state.<locals>._update_widget_state(event=<Event blocked=False handled=False native=None source=None sources=[] type='dask'>)
    262 def _update_widget_state(event):
--> 263     widget.state = {name: event.value}
        {name: event.value} = {'dask': DaskSettings(enabled=False, cache=4.29)}
        widget = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object at 0x1651031b0>
        name = 'dask'
        event.value = DaskSettings(enabled=False, cache=4.29)
        event = <Event blocked=False handled=False native=None source=None sources=[] type='dask'>

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/utils.py:13, in StateProperty.setter.<locals>._setter(*args=(<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object>, {'dask': DaskSettings(enabled=False, cache=4.29)}))
     11 *head, value = args
     12 if value is not None:
---> 13     fset(*head, value)
        fset = <function ObjectSchemaWidgetMinix.state at 0x16a04f880>
        value = {'dask': DaskSettings(enabled=False, cache=4.29)}
        head = [<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object at 0x1651031b0>]

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py:702, in ObjectSchemaWidgetMinix.state(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object>, state={'dask': DaskSettings(enabled=False, cache=4.29)})
    699 @state.setter
    700 def state(self, state: dict):
    701     for name, value in state.items():
--> 702         self.widgets[name].state = value
        name = 'dask'
        value = DaskSettings(enabled=False, cache=4.29)
        self.widgets[name] = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object at 0x16510ed50>
        self.widgets = {'language': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x1651036b0>, 'save_window_geometry': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.CheckboxSchemaWidget object at 0x165102df0>, 'save_window_state': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.CheckboxSchemaWidget object at 0x165103bb0>, 'gui_notification_level': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x165103e30>, 'console_notification_level': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x165102710>, 'playback_fps': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.SpinSchemaWidget object at 0x1651037f0>, 'playback_mode': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x165103b10>, 'grid_stride': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.SpinSchemaWidget object at 0x165101f90>, 'grid_width': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.SpinSchemaWidget object at 0x16510fb10>, 'grid_height': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.SpinSchemaWidget object at 0x16510f890>, 'confirm_close_window': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.CheckboxSchemaWidget object at 0x16510f610>, 'hold_button_delay': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.SpinDoubleSchemaWidget object at 0x16510f2f0>, 'brush_size_on_mouse_move_modifiers': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x16510f070>, 'dask': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object at 0x16510ed50>, 'new_labels_dtype': <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.EnumSchemaWidget object at 0x16510e530>}
        self = <napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.ObjectSchemaWidget object at 0x1651031b0>

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/utils.py:13, in StateProperty.setter.<locals>._setter(*args=(<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object>, DaskSettings(enabled=False, cache=4.29)))
     11 *head, value = args
     12 if value is not None:
---> 13     fset(*head, value)
        fset = <function ObjectSchemaWidgetMinix.state at 0x16a04f880>
        value = DaskSettings(enabled=False, cache=4.29)
        head = [<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object at 0x16510ed50>]

File ~/Dev/napari/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py:701, in ObjectSchemaWidgetMinix.state(self=<napari._vendor.qt_json_builder.qt_jsonschema_form.widgets.HorizontalObjectSchemaWidget object>, state=DaskSettings(enabled=False, cache=4.29))
    699 @state.setter
    700 def state(self, state: dict):
--> 701     for name, value in state.items():
        state = DaskSettings(enabled=False, cache=4.29)
    702         self.widgets[name].state = value

AttributeError: 'DaskSettings' object has no attribute 'items'
```

</details>

It's not clear whether the setting is actually set/unset properly.

Note: no traceback occurs on 0.4.19, so this is a regression in `main`

### 💡 Steps to Reproduce

Open napari.
Access Settings > Application (macOS Command-comma)
Toggle the Enabled box:
<img width="456" alt="image" src="https://github.com/napari/napari/assets/76622105/c4103d0f-9398-42a5-96da-97cc2de849d0">

### 💡 Expected Behavior

No traceback.

### 🌎 Environment

napari: 0.5.0a2.dev720+gb00d7381b
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.3.1
VisPy: 0.14.3.dev18
magicgui: 0.8.2
superqt: 0.6.7
in-n-out: 0.2.0
app-model: 0.2.5
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Optional:
- numba: 0.59.0
- triangle not installed

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

### 💡 Additional Context

Does the setting even work?
Maybe it doesn't work at all, so Dask Cache isn't used which could explain poor behavior with zarr, as seen here:
https://forum.image.sc/t/viewing-zarr-via-s3-in-napari-is-extremely-slow/97941/5?u=psobolewskiphd

**Comment by psobolewskiPhD** [comment]
Git bisect points to: d51c1ce5ba6845f05a95bf7fed84648b4218fa42
Unintended consequences and not caught by tests 😭 
@dalthviz if you get a chance, can you take a look?

**Comment by psobolewskiPhD** [comment]
Using:
`get_settings().application.dask` suggests the setting is being honored regardless of the traceback...
