### ISSUE TITLE
Cannot import "thread_worker" in dock_widget plug-in (circular import?)

### ISSUE THREAD

**Issue by sommerc** [napari/napari#2586]
## 🐛 Bug

Similar to issue #2116, I am not able to import the napari `worker_thread` in my plugin code,

## To Reproduce

A minimal plug-in

```python
from qtpy.QtWidgets import QWidget
from napari_plugin_engine import napari_hook_implementation

from napari.qt.threading import thread_worker ### <- triggers error

@napari_hook_implementation(specname="napari_experimental_provide_dock_widget")
def test_widget():
    return (TestWidget, {"area": "right"})


class TestWidget(QWidget):
    def __init__(self) -> None:
        super().__init__()
```

yields following traceback, when `thread_worker` is imported.

```python
      2 from napari_plugin_engine import napari_hook_implementation
----> 3 from napari.qt.threading import thread_worker
        global napari.qt.threading = undefined
        global thread_worker = undefined
      4 

c:\users\csommer\src\napari\napari\qt\__init__.py in 
      2 
----> 3 from .._qt.qt_event_loop import get_app, run
        global _qt.qt_event_loop = undefined
        global get_app = undefined
        global run = undefined
      4 from .._qt.qt_main_window import Window

c:\users\csommer\src\napari\napari\_qt\__init__.py in 
     39 
---> 40 from .qt_event_loop import get_app, gui_qt, quit_app, run
        global qt_event_loop = undefined
        global get_app = undefined
        global gui_qt = undefined
        global quit_app = undefined
        global run = undefined
     41 from .qt_main_window import Window

c:\users\csommer\src\napari\napari\_qt\qt_event_loop.py in 
     19 from ..utils.perf import perf_config
---> 20 from ..utils.settings import SETTINGS
        global utils.settings = undefined
        global SETTINGS = undefined
     21 from .dialogs.qt_notification import NapariQtNotification

ImportError: cannot import name 'SETTINGS' from partially initialized module 'napari.utils.settings' (most likely due to a circular import) (c:\users\csommer\src\napari\napari\utils\settings\__init__.py)
```

## Environment

in current master

**Comment by tlambert03** [comment]
thank you for reporting.  We are aware of the regression (see also #2574) and it should be fixed in #2575, with some additional follow up PRs to try to prevent it in the future.

For now, you can work around the issue by delaying the import and putting it in the body of the method or function where you'd like to use it

**Comment by sofroniewn** [comment]
Thanks for the report! Looks like this was closed by #2575, feel free to reopen if that isn't the case!!

**Comment by sommerc** [comment]
Thanks a lot!
