### PR TITLE
Implement lazy module importing for all public submodules

### LINKED ISSUE #2810: napari.layers cannot be found on master
## 🐛 Bug

Probably introduced in #2662, one can no longer do:

```python
import numpy as np
import napari

image = napari.layers.Image(np.random.random((500, 500)))
```

Trying this on master, I get:

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/projects/napari/napari/__init__.py in __getattr__(name)
     75     try:
---> 76         return locals()[name]
     77     except KeyError:

KeyError: 'layers'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-c7cb80ce1324> in <module>
----> 1 layer = napari.layers.Image(np.random.random((500, 500)), scale=[10, 10])

~/projects/napari/napari/__init__.py in __getattr__(name)
     76         return locals()[name]
     77     except KeyError:
---> 78         raise AttributeError(f"module 'napari' has no attribute {name!r}")

AttributeError: module 'napari' has no attribute 'layers'
```

`from napari import layers` works fine, so the module is there. :grimacing: 

This is an API breakage so it unfortunately needs to be fixed before 0.4.9.

### PR DESCRIPTION
**Pull request by jni**
# Description

Fixes #2810

Many thanks to @stefanv and scikit-image/scikit-image#5101 for the precedent.

### CODE REVIEW

**Comment by tlambert03** [comment]
you'll need to add back all of the non-module exports too, like `napari.run`, `view_image`,  etc...

**Comment by jni** [comment]
Gah, fix incoming. LOL

**Review by tlambert03 — APPROVED** [review]
lovely!  thanks

File: napari/_lazy.py [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+    __all__ = list(submodules | attr_to_modules.keys())
+
+    def __getattr__(name):
+        # this unused import is here to fix a very strange bug.
+        # there is some mysterious magical goodness in scipy stats that needs
+        # to be imported early.
+        # see: https://github.com/napari/napari/issues/925
+        # see: https://github.com/napari/napari/issues/1347
+        from scipy import stats  # noqa: F401
```
Comment (stefanv) [inline napari/_lazy.py:43]: What is this about?

**Comment by stefanv** [comment]
Please keep an eye on the skimage PR; I may still improve that implementation, but it should then be as simple as copying the file here.

File: napari/_lazy.py (hunk 1 above)
Comment (jni) [reply napari/_lazy.py:43]: Read the comments just above it. It's weird. 😂

**Review by sofroniewn — APPROVED** [review]
LGTM! Can merge after all tests pass, thanks all!!

File: napari/_lazy.py (hunk 1 above)
Comment (tlambert03) [reply napari/_lazy.py:43]: yeah, we honestly still don't know... the relationship with scipy.stats was first observed in https://github.com/napari/napari/issues/925#issuecomment-580059473... tried to take it out  in https://github.com/napari/napari/pull/1250, and then https://github.com/napari/napari/issues/1347 popped up again.  would be thrilled if you had any insighty
