### PR TITLE
fix error message when no reader available

### LINKED ISSUE #4253: AttributeError trying to test file opening with a plugin
## 🐛 Bug

I am trying to test the automatic opening of a file with a `napari` plugin. When running `pytest` on the test code below, I get the following error.

I suspect that I'm doing something wrong here, and that the solution to this issue would be to improve the error message (perhaps no plugings are acutally registered? perhaps it's not possible to do this type of testing?)

```python
_________________________________________________________ test_load_cellfinder_xml __________________________________________________________

path = '/Users/dstansby/projects/napari/brainglobe-napari-io/brainglobe_napari_io/tests/data/cell_classification.xml', plugin = None

# Rest of function cut out for readability

        layer_data = None
        result = hook_caller.call_with_result_obj(path=path)
        reader = result.result  # will raise exceptions if any occurred
        try:
>           layer_data = reader(path)  # try to read data
E           TypeError: 'NoneType' object is not callable

../../../mambaforge/envs/napari/lib/python3.9/site-packages/napari/plugins/io.py:108: TypeError

During handling of the above exception, another exception occurred:

viewer = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 0.0,...ine at 0x15a8773a0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x15a877f70>})

    def test_load_cellfinder_xml(viewer):
>       viewer.open(test_data_path / 'cell_classification.xml')

brainglobe_napari_io/tests/test_brainglobe_napari_io.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../mambaforge/envs/napari/lib/python3.9/site-packages/napari/components/viewer_model.py:907: in open
    self._add_layers_with_plugins(
../../../mambaforge/envs/napari/lib/python3.9/site-packages/napari/components/viewer_model.py:952: in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
../../../mambaforge/envs/napari/lib/python3.9/site-packages/napari/plugins/io.py:111: in read_data_with_plugins
    raise PluginCallError(result.implementation, cause=exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PluginCallError(None), hook_implementation = None, msg = None, cause = TypeError("'NoneType' object is not callable")

    def __init__(self, hook_implementation, msg=None, cause=None):
>       plugin = hook_implementation.plugin
E       AttributeError: 'NoneType' object has no attribute 'plugin'

../../../mambaforge/envs/napari/lib/python3.9/site-packages/napari_plugin_engine/exceptions.py:197: AttributeError
```

## To Reproduce

```python
@pytest.fixture
def viewer(make_napari_viewer):
    viewer = make_napari_viewer()
    plugin_manager.register(plugin_namespace)
    return viewer


def test_load_cellfinder_xml(viewer):
    viewer.open(test_data_path / 'cell_classification.xml')
```
## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This fixes the error message that one gets when no reader is available (a regression introduced in #4026), and adds a test
fixes #4253

### CODE REVIEW

**Review by nclack — APPROVED** [review]
lgtm!

**Comment by dstansby** [comment]
Amazing, thanks for the quick fix!
