### PR TITLE
Add option to use npe2 shim/adaptor for npe1 plugins

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
A "softer/gentler" version of #4015.  This PR adds a new setting (`settings.plugin.use_npe2_adaptor`) that lets the user opt-in to the npe2-adaptor behavior.  It defaults to `False`, but when set to `True`, it will essentially treat _all_ plugins as npe2 plugins.  This means that:

- upon first import after enabling this setting, npe1 plugins will imported as usual, but their contributions will be indexed and  stored in a cached npe2 "shim" manifest (see https://github.com/napari/npe2/pull/126). 
- after the first time running napari with this option on, later boots of napari will incur *no* penalty for importing and discovering plugin contributions. 🎉
- each plugin will be imported lazily, only when one of their contributions is requested.
- (adapter caches can be managed using `npe2 cache --help`)
- the `discovery` method on the old `napari.plugins.plugin_manager` becomes a no-op.  In a later version, i hope to make this shim the _only_ option for npe1, at which point all the npe1-specific code in the repo can go away (like #4015)

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

File: napari/_qt/dialogs/qt_plugin_dialog.py [hunk 1]
```diff
@@ -808,7 +813,9 @@ def _add_to_installed(distname, enabled, npe_version=1):
             if distname in self.already_installed or distname == 'napari':
                 continue
             enabled = not pm2.is_disabled(manifest.name)
-            _add_to_installed(distname, enabled, npe_version=2)
+            # if it's an Npe1 adaptor, call it v1
+            npev = 'shim' if 'npe1' in type(manifest).__name__.lower() else 2
```
Comment (DragaDoncila) [inline napari/_qt/dialogs/qt_plugin_dialog.py:817]: what is `type(manifest).__name__.lower()` actually checking sorry? Just curious how we're discerning between the different manifests, I have no issue with it.

File: napari/_qt/dialogs/qt_plugin_dialog.py [hunk 2]
```diff
@@ -378,11 +377,17 @@ def __init__(
             self.action_button.setText(trans._("install"))
             self.action_button.setObjectName("install_button")
 
-    def _handle_npe2_plugin(self):
+    def _handle_npe2_plugin(self, npe_version):
+        if npe_version == 1:
+            return
+        opacity = 0.4 if npe_version == 'shim' else 1
+        lbl = 'npe1 (adapted)' if npe_version == 'shim' else 'npe2'
```
Comment (DragaDoncila) [inline napari/_qt/dialogs/qt_plugin_dialog.py]: 😍  very cute

**Review by DragaDoncila — COMMENTED** [review]
I really like this. Pulled it down and it works like a charm. Only "issue" I've discovered is that plugins are now indexed strictly by package name, whereas for `npe1` plugins I think it was module? E.g. a "shimmed" `napari_tifffile` now shows up as `napari-tifffile`. Not a huge deal, but can break preferences.

**Comment by DragaDoncila** [comment]
Ok a bigger issue is that now `builtins` doesn't work, and `napari` (the npe2 plugin) only declares `['*.csv', '*.npy']` in its `filename_patterns`. 

Also, oddly, if I call 

```python
viewer.open('../data/man_seg002.tif', plugin='napari')
```

I get 

```python
ValueError: There is no registered plugin named 'napari'.
Names of plugins offering readers are: set()
```

but if I have `napari-tifffile` installed and run `viewer.open('../data/man_seg002.tif', plugin='napari')`, it opens with `napari-tifffile`?

```python
viewer.open('../data/man_seg002.tif', plugin='napari')
Out[3]: [<Image layer 'man_seg002 [1]' at 0x7fa5146ba260>]

viewer.layers[-1].source
Out[4]: Source(path='../data/man_seg002.tif', reader_plugin='napari-tifffile', sample=None, widget=None)
```

FWIW I don't think this is directly tied to this PR, but maybe just leftover because we still have both `builtins` and `napari` lying around? I'm just wondering whether, now that we're shimming, this will become even muddier.

See also #4575 where @jni and I realized we probably need to show both.

File: napari/_qt/dialogs/qt_plugin_dialog.py (hunk 1 above)
Comment (tlambert03) [reply napari/_qt/dialogs/qt_plugin_dialog.py:817]: it's checking the name of the class, to make sure it's `NPE1Adapter` :joy: ... it could be an `isinstance`, but requires an import from private module.  I dunno 🤷

**Comment by tlambert03** [comment]
with #4668 merged into this PR, these issues seem fixed.  @DragaDoncila  can you confirm?

**Comment by DragaDoncila** [comment]
@tlambert03 yep, definitely. The issue was more with our manifest than with the shim. I didn't realize initially that in `builtins.yaml` we were pointing to the same reader function as we always have, and just hadn't correctly added all the filename patterns.

**Comment by DragaDoncila** [comment]
Although I had already opened a PR for this... But we just missed it in release. @tlambert03 see #4580

**Comment by tlambert03** [comment]
updated to include #4668

**Comment by tlambert03** [comment]
with https://github.com/napari/napari/pull/4668 merged into main, I think this is working.  Would be good to get some eyes on this from @napari/core-devs

File: napari/_qt/dialogs/qt_plugin_dialog.py (hunk 1 above)
Comment (DragaDoncila) [reply napari/_qt/dialogs/qt_plugin_dialog.py:817]: I think that's fine, but I think it would be more explicit to just have `'shim' if type(manifest).__name__ == 'NPE1Adapter' else 2` and then even a comment that we're avoiding a private import

File: napari/plugins/__init__.py [hunk 3]
```diff
@@ -46,9 +46,14 @@ def _initialize_plugins():
     if 'napari' in _from_npe2:
         _from_npe2.update({'napari', 'builtins'})
     plugin_manager._skip_packages = _from_npe2
-
     plugin_manager._blocked.update(settings.plugins.disabled_plugins)
-    plugin_manager._initialize()
+
+    if settings.plugins.use_npe2_adaptor:
+        # prevent npe1 plugin_manager discovery
```
Comment (DragaDoncila) [inline napari/plugins/__init__.py:52]: So just to clarify, if I use this option I will *never* see an npe1 plugin (what a dream...). For my own reference, do we have an idea of what percentage of current npe1 plugins (if any) cannot be auto converted?

**Review by DragaDoncila — APPROVED** [review]
I love this, works as expected and is super exciting :tada: . I have just a few comments, which I don't think need to be addressed now, while this is still optional, but should be addressed before we remove the original `napari_plugin_manager` entirely:

- When setting the preference for the first time, or installing new plugins (in the GUI), a restart is required for the plugins to be shimmed. We may want to add a warning or some such, and ideally for newly installed plugins, they would be shimmed on install so the user doesn't have to restart.
- I played around with a few plugins and most converted just fine. However, when I installed `btrack` and then restarted napari, I got `napari.manifest -> 'btrack' could not be imported: Could not find file 'napari.yaml' in module 'btrack'` in the terminal. I assume there was some conversion issue, but it would be nice if this was flagged more prominently for the GUI user somehow... 
- I think some plugins will now change their registered name in the plugin manager, and this may lead to preferences being incorrect. In the GUI I think this is okay as the user will be prompted to select a different plugin (so they have an out), but maybe we could let them know explicitly why this is happening, or convert their preferences silently maybe? Not sure about that last bit.

File: napari/plugins/__init__.py (hunk 3 above)
Comment (tlambert03) [reply napari/plugins/__init__.py:52]: > For my own reference, do we have an idea of what percentage of current npe1 plugins (if any) cannot be auto converted?

when I created the shim, I tested all plugins (here: https://github.com/napari/npe2/pull/132) ... at the time 21 out of the 143 plugins tested actually need the shim thing at all (in the sense that they had locally defined contributions). all the rest have direct python_names for all their assets.  And the shim strategy appeared to work for all 21 of those.  So, based on those tests, this should work fine for _all_ plugins.  The one exception is napari tools menu, which is not actually a plugin, but a monkeypatch that just hijacks the loading system

**Comment by tlambert03** [comment]
> I got napari.manifest -> 'btrack' could not be imported: Could not find file 'napari.yaml' in module 'btrack'

**Comment by tlambert03** [comment]
> I got napari.manifest -> 'btrack' could not be imported: Could not find file 'napari.yaml' in module 'btrack' 

thanks will have a look

**Comment by tlambert03** [comment]
> I played around with a few plugins and most converted just fine. However, when I installed btrack and then restarted napari, I got napari.manifest -> 'btrack' could not be imported: Could not find file 'napari.yaml' in module 'btrack' in the terminal. I assume there was some conversion issue, but it would be nice if this was flagged more prominently for the GUI user somehow...

looked into this.  It's unrelated to this PR and is a packaging issue in btrack.  Fixed submitted https://github.com/quantumjot/BayesianTracker/pull/153

**Review by jni — APPROVED** [review]
I really like this too. As noted in private conversation with @tlambert03, it would be good if the option linked to text that explained the consequences of that choice, which are:

- shimmed plugin widgets lose the ability to specify in which docked area they live (left, right, bottom)
- reader call order isn't a thing anymore

Both of those are going away though so I'm happy to ease users into the transition with this. Good stuff.

File: napari/settings/_plugins.py [hunk 4]
```diff
@@ -25,6 +25,16 @@ class PluginAPI(str, Enum):
 
 
 class PluginsSettings(EventedModel):
+    use_npe2_adaptor: bool = Field(
+        False,
+        title=trans._("Use npe2 adaptor"),
+        description=trans._(
```
Comment (nclack) [inline napari/settings/_plugins.py:31]: maybe out-of-scope, but it would be cool to reflect this description into a tooltip for the corresponding thing in the properties panel.

**Review by nclack — APPROVED** [review]
I love this so much.

Agree with @jni, it would be good to note the behavioral differences for the user. The startup behavior is another thing that should be added to that list - especially since it should be a positive for most folks.

File: napari/_qt/dialogs/qt_plugin_dialog.py (hunk 2 above)
Comment (andy-sweet) [inline napari/_qt/dialogs/qt_plugin_dialog.py]: As it's going to be a label, should `'adapted'` be a translated string?

File: napari/_qt/dialogs/qt_plugin_dialog.py [hunk 5]
```diff
@@ -378,11 +377,17 @@ def __init__(
             self.action_button.setText(trans._("install"))
             self.action_button.setObjectName("install_button")
 
-    def _handle_npe2_plugin(self):
+    def _handle_npe2_plugin(self, npe_version):
+        if npe_version == 1:
```
Comment (andy-sweet) [inline napari/_qt/dialogs/qt_plugin_dialog.py:381]: Looks like `npe_version` is sometimes an `int` and sometimes a `str`. Optional, but is it worth considering an enum here? Or do you mostly want this to be an `int` and the `str` is a special case that we can just live with for now?

**Review by andy-sweet — COMMENTED** [review]
I don't understand all the implications of this PR, but the changes looks good. Maybe a missing translation.

File: napari/settings/_plugins.py (hunk 4 above)
Comment (tlambert03) [reply napari/settings/_plugins.py:31]: that was actually the original intention for these descriptions.  but it looks like preferences are no longer doing this.  yeah: another PR

File: napari/_qt/dialogs/qt_plugin_dialog.py (hunk 5 above)
Comment (tlambert03) [reply napari/_qt/dialogs/qt_plugin_dialog.py:381]: yeah, this is gonna be gone pretty soon anyway (with #4692), and since it's a very minimally used internally function, I think an Enum is overkill

File: napari/_qt/dialogs/qt_plugin_dialog.py (hunk 2 above)
Comment (tlambert03) [reply napari/_qt/dialogs/qt_plugin_dialog.py]: done

**Comment by tlambert03** [comment]
I added a document with some additional explanation at https://github.com/napari/napari/pull/4564/files#diff-37b9bdb893f94908825ca80e038f5912fcf30bbc91f34eb313529680c16a14d1

I'm not sure how to link to it in the preferences pane (I tried an anchor tag but it doesn't work).  The tooltip _does_ pop up, but only if you hover over the checkbox (not the label).  I think it's a bit out of scope here to figure out how to add web links to the preferences pane.  so hopefully having the document there is enough

**Review by jni — APPROVED** [review]
❤️

**Comment by jni** [comment]
Thanks everyone for the reviews! I'll give this another ~24h before merging (or @tlambert03 feel free to self-merge if it's just sitting here without comment).

The macos 3.10 build is [failing](https://github.com/napari/napari/runs/6928000667?check_suite_focus=true) which what appears to be a numcodecs compilation error? That could be due to an updated macos image. I notice that there's no 3.10 wheels for numcodecs, but a new release is being worked on (0.10.0a3 was released in March, and does have 3.10 wheels), so presumably this problem will resolve itself. If we want to fix it beforehand, installing numcodecs with conda is an option. But either way, the failure is unrelated to this PR.
