### ISSUE TITLE
napari.layers cannot be found on master

### ISSUE THREAD

**Issue by jni** [napari/napari#2810]
## 🐛 Bug

Probably introduced in #2662, one can no longer do:

```python
import numpy as np
import napari

image = napari.layers.Image(np.random.random((500, 500)))
```

Trying this on master, I get:

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/projects/napari/napari/__init__.py in __getattr__(name)
     75     try:
---> 76         return locals()[name]
     77     except KeyError:

KeyError: 'layers'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-c7cb80ce1324> in <module>
----> 1 layer = napari.layers.Image(np.random.random((500, 500)), scale=[10, 10])

~/projects/napari/napari/__init__.py in __getattr__(name)
     76         return locals()[name]
     77     except KeyError:
---> 78         raise AttributeError(f"module 'napari' has no attribute {name!r}")

AttributeError: module 'napari' has no attribute 'layers'
```

`from napari import layers` works fine, so the module is there. :grimacing: 

This is an API breakage so it unfortunately needs to be fixed before 0.4.9.

**Comment by goanpeca** [comment]
>This is an API breakage so it unfortunately needs to be fixed before 0.4.9.

Indeed :) 

---

The bug is not strictly `high-severity` since there is a workaround. The severity is pretty low when there is a workaround however annoying the bug may be.

Higher severities are associated with napari actually breaking, segfaulting without any means for the users to have a workaround to get napari running 🤓

**Comment by goanpeca** [comment]
On another note, I have seen this happen on some other packages (even python standard library itself I think) so the question I have (in general) once you import the top module, should you be able to access any submodule from it 🤔 ?

**Comment by tlambert03** [comment]
yeah, we've never exported `layers` in the napari namespace... so this has worked in the past due to other inner modules importing it.

> once you import the top module, should you be able to access any submodule from it

not automatically, it depends on what else imports it.  For instance, take this package structure:

```
my_module/
├─ __init__.py
├─ a.py
├─ b.py
```
where `a.py` and `b.py` are empty and 

```python
# __init__.py
from . import a
```

```python
In [1]: import my_module

In [2]: my_module.a
Out[2]: <module 'my_module.a' from '~/my_module/a.py'>

In [3]: my_module.b
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5cb7b5e01231> in <module>
----> 1 my_module.b

AttributeError: module 'my_module' has no attribute 'b'
```

however, if within `a.py` you import `b`:

```python
# a.py
from . import b
```

then it works as @jni was expecting in the first post:
```python
In [1]: import my_module

In [2]: dir(my_module)
Out[2]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'a',
 'b']

In [3]: my_module.b
Out[3]: <module 'my_module.b' from '~/my_module/b.py'>
```

So basically, the fact that it worked before was an indirect import of `napari.layers` somewhere inside some other module that we do export in `napari.__init__`.  The `__getattr__` approach definitely requires you to be explicit about the namespace of the top level package ... but I'm not sure that's a bad thing?

**Comment by goanpeca** [comment]
>The __getattr__ approach definitely requires you to be explicit about the namespace of the top level package ... but I'm not sure that's a bad thing?

Well it is a convenience, and it was like that before (for other reasons) but I do not think being explicit about the imports is bad either.

**Comment by tlambert03** [comment]
ok.  I've played with this a little and while I can fix `layers` pretty easily with the `__getattr__`, it's not as easy for all of the things (`experimental` for instance is giving me circular import problems with the approaches I've tried).  So if we want to get back the behavior of being able to import `napari` and then access all of the top level modules implicitly, we may want to roll back #2662 as well... 

which will of course bring back the double import problem in `__main__`
@jni, are you still feeling pretty strongly about keeping the cli module inside `napari.__main__`?

**Comment by goanpeca** [comment]
>So if we want to get back the behavior of being able to import napari and then access all of the top level modules implicitly, we may want to roll back #2662 as well...

[PR](https://github.com/napari/napari/pull/2760) on settings is now depending on that behavior :(

**Comment by jni** [comment]
> I can fix layers pretty easily with the __getattr__, it's not as easy for all of the things (experimental for instance is giving me circular import problems with the approaches I've tried)

Hmm, that sucks, but I suspect there is a solution somewhere. Don't have time to look at this in detail right now but there is discussion happening about this pattern at the scipy ecosystem level — here is the [scikit-image PR](https://github.com/scikit-image/scikit-image/pull/5101) and the [SPEC discussion](https://discuss.scientific-python.org/t/spec-1-lazy-loading-for-submodules/25/3). As you can see the skimage PR went for aaaaaages so there's certainly a lot of subtlety, but it might be "done" now.

**Comment by jni** [comment]
> yeah, we've never exported layers in the napari namespace... so this has worked in the past due to other inner modules importing it.

I did wonder about that, but I was excited to see it work in my usage and then got used to it! 😂

**Comment by jni** [comment]
@goanpeca feel free to correct my label usage. 😊

**Comment by tlambert03** [comment]
i'd say lets just roll it back, and deal with the slow imports some other way

**Comment by tlambert03** [comment]
I'm sure it can "be done" ... but after playing with it for 30 minutes or so, it started to feel like a rabbit hole of magic that's going to be a continual frustration (and it also exposed that we've been relying on python imports and `sys.modules` being even cooler than we knew behind the scenes for us).

**Comment by jni** [comment]
Just chatting with @stefanv now, he says all the magic is here:

https://github.com/scikit-image/scikit-image/pull/5101/files#diff-cd88cca5d4b70042d79332dc7132ad42a8ea07929b479cf64be5bddb1f7f0548R5

and here:

https://github.com/scikit-image/scikit-image/pull/5101/files#diff-5cf0c3839f5afeb18eb878337af2a47e09d91e50080d007d9c3f5123659ce2d8R96-R97

so we should be able to copy that `lazy.py` and use it. Imma give it a try.

**Comment by jni** [comment]
Working now (locally tested at least) in #2816. 🤞 for the CI!
