### ISSUE TITLE
Layer order not always remaining synchronized

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1467]
## 🐛 Bug
See https://forum.image.sc/t/certain-layers-mysteriously-invisible-when-removing-then-re-adding-layers/40484, where user naten7k shared this script:
```python
import napari
import numpy as np

with napari.gui_qt():
    viewer = napari.Viewer()
    image = np.random.rand(1000,1000)
    points = np.random.rand(100, 2) * 1000
    shapes = [np.random.rand(10,2) * 1000 for x in range(10)]
    
    viewer.add_image(image)
    viewer.add_shapes(shapes, shape_type='polygon')
    viewer.add_points(points)

    # remove and re-add image    
    viewer.layers.remove('image')
    viewer.add_image(image, name='image')
    
    # remove non-image data
    viewer.layers.remove('shapes')
    viewer.layers.remove('points')
    # add it back
    viewer.add_shapes(shapes, shape_type='polygon')
    viewer.add_points(points)
   # and mysteriously, shapes is not visible
```

at the end of that script, the shapes are not visible even though they are in front of the image:
```
[viewer.window.qt_viewer.layer_to_visual[x].order for x in viewer.layers]
# output is [3,2,3] ... so two layers erroneously have the same value
```
there's probably a quick fix, but I will also mention a conversation that @sofroniewn and I had recently about this: this is a good example of the multiple-sources-of-truth problem.  Ideally, the visual.node.order would be a dynamic property that pulled the index of the layer in the LayerList when needed, rather than something that was help independently on the node.  That's a bit tricky because this is a vispy class, but we could create a subclass that knew how to retrieve the proper order from a provided layerlist.

**Comment by sofroniewn** [comment]
I'm 99.9% confident this will be fixed in #1463 (see the addition of the missing `node.order` call) which I submitted this morning and is waiting on me writing a test, which I can do tonight. Note the bug was introduced 2 days ago in #1445 and we had no test that would have caught it back then.

**Comment by sofroniewn** [comment]
> good example of the multiple-sources-of-truth problem

That's fair enough, with that approach the missing line in #1463 wouldn't have been needed, but what I'm taking away more right now from our bugs around refactoring is not that we need more refactoring, but that we need more comprehensive GUI tests, which we've always been lagging on - see https://github.com/napari/napari/pull/1464#issuecomment-659609094.

**Comment by tlambert03** [comment]
> I'm 99.9% confident this will be fixed in #1463 (see the addition of the missing `node.order` call) which I submitted this morning and is waiting on me writing a test, which I can do tonight. Note the bug was introduced 2 days ago in #1445 and we had no test that would have caught it back then.

awesome! great to know you're way ahead on this! :) 
agree 100% on the tests!

**Comment by sofroniewn** [comment]
> I'm 99.9% confident this will be fixed in #1463 (see the addition of the missing node.order call) which I submitted this morning and is waiting on me writing a test, which I can do tonight. Note the bug was introduced 2 days ago in #1445 and we had no test that would have caught it back then.

Good thing I gave myself 0.01% wiggle room on that one, you never know when you're going to need it ;-) Turns out this is not fixed by #1463 nor was it introduced by #1445, it is present on `0.3.5` (I should have asked that first!).

I think I know what's causing it now though, and I might add test and fix to #1463. I will give @tlambert03 that the synchronization of the `node` and `layer` here has gone awry and not having to deal with that would be nice!!

**Comment by sofroniewn** [comment]
Ok fix + test for this now in #1463

**Comment by Czaki** [comment]
I meet something similar. When I add layers and then remover previous one (to avoid blinking).

Then there is problem with identify active layers ex:

```
AttributeError: 'NoneType' object has no attribute 'coordinates'
  File "vispy/app/backends/_qt.py", line 447, in mousePressEvent
    modifiers=self._modifiers(ev),
  File "vispy/app/base.py", line 181, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "PartSeg/segmentation_mask/image_view.py", line 57, in component_click
    cords = np.array([int(x) for x in self.viewer.active_layer.coordinates])
```

in my case I fix it with such code:
```python
        self.viewer.layers.unselect_all()
        for el in layer_list:
            index = self.viewer.layers.index(el)
            self.viewer.layers.move_selected(index, len(self.viewer.layers))
```
where `layer_list` is list of layers to remove. 

So it looks like some information are not properly updated on remove layers.
