### PR TITLE
Fix min_req CI failures by bumping typing_extensions

### LINKED ISSUE #7107: `min_req` tests failing due to `setuptools` release
So looking more at the [failure](https://github.com/napari/napari/actions/runs/10000405066/job/27642895582?pr=7106#step:13:603) with `min_req` tests, it looks like `setuptools` is doing an `Any` `import` from `typing_extensions`, and they released last night and we don't have an upper pin

```python
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/setuptools/_vendor/typeguard/_checkers.py", line 71, in <module>
      from typing_extensions import Any as SubclassableAny
  ImportError: cannot import name 'Any' from 'typing_extensions' (/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/typing_extensions.py)
```

_Originally posted by @DragaDoncila in https://github.com/napari/napari/issues/7106#issuecomment-2237912752_

### PR DESCRIPTION
**Pull request by jni**
Fixes #7107

A new setuptools release started using
`from typing_extensions import Any`, which is only available in
typing_extensions 4.4 and greater. It seems that setuptools is used
during testing, which causes tests to fail with an ImportError.

**Edit:** After updating to 4.4, there was a new error from
setuptools:

```pytb
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/setuptools/_vendor/typeguard/_importhook.py", line 22, in <module>
      from typing_extensions import Buffer
  ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/typing_extensions.py)
```

The Buffer type was only added in 4.6, so I've further bumped the
dependency from 4.4 to 4.6.

### CODE REVIEW

**Comment by jni** [comment]
Ugh. [New failure](https://github.com/napari/napari/actions/runs/10003108098/job/27650858351?pr=7108#step:13:198) is reproducible:

```pytb
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/npe2/manifest/__init__.py", line 1, in <module>
      from ._package_metadata import PackageMetadata
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
      exec(co, module.__dict__)
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/npe2/manifest/_package_metadata.py", line 20, in <module>
      class PackageMetadata(BaseModel):
    File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
    File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
    File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
    File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
    File "pydantic/fields.py", line 633, in pydantic.fields.ModelField._type_analysis
    File "pydantic/fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
    File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
    File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
    File "pydantic/fields.py", line 638, in pydantic.fields.ModelField._type_analysis
    File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/typing.py", line 852, in __subclasscheck__
      return issubclass(cls, self.__origin__)
  TypeError: issubclass() arg 1 must be a class
  /home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/coverage/control.py:888: CoverageWarning: No data was collected. (no-data-collected)
    self._warn("No data was collected.", slug="no-data-collected")
  py39-linux-pyqt5-cov: exit 1 (2.71 seconds) /home/runner/work/napari/napari> coverage run -m pytest --color=yes --basetemp=/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/tmp --ignore tools --maxfail=5 --json-report --pystack-threshold=60 --pystack-args=--native-all --json-report-file=/home/runner/work/napari/napari/report-py39-linux-pyqt5-cov.json --basetemp=.pytest_tmp --save-leaked-object-graph pid=7909
  py39-linux-pyqt5-cov: FAIL code 1 (16.99=setup[14.28]+cmd[0.00,2.71] seconds)
  evaluation failed :( (17.28 seconds)
Error: The process '/usr/bin/bash' failed with exit code 1
The process '/usr/bin/bash' failed with exit code 1
```
