### PR TITLE
Use dtype.type when passing to downstream NumPy functions

### PR DESCRIPTION
**Pull request by jni**
# Description

This works with both NumPy dtypes and data types from other array libraries such as tensorstore.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
Change looks good, but we've got some failing tests

**Comment by jni** [comment]
Ugh. Turns out it's pretty finicky to make dtypes work generally across all duck-array types:

```python
In [1]: np.uint8.type
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c60fb0eb7e75> in <module>
----> 1 np.uint8.type

AttributeError: type object 'numpy.uint8' has no attribute 'type'

In [2]: np.dtype(np.uint8).type
Out[2]: numpy.uint8

In [4]: import tensorstore as ts

In [5]: ts.uint8
Out[5]: dtype("uint8")

In [6]: ts.uint8.type
Out[6]: numpy.uint8

In [7]: np.dtype(ts.uint8)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3f2a10f02536> in <module>
----> 1 np.dtype(ts.uint8)

TypeError: Cannot interpret 'dtype("uint8")' as a data type

In [8]: np.dtype(np.uint8)
Out[8]: dtype('uint8')

In [9]: np.dtype(np.uint8).type
Out[9]: numpy.uint8

In [10]: np.dtype(np.dtype(np.uint8))
Out[10]: dtype('uint8')

In [11]: type(np.dtype('uint8'))
Out[11]: numpy.dtype

In [12]: type(np.dtype('uint8').type)
Out[12]: type

In [13]: type(ts.uint8)
Out[13]: tensorstore.dtype

In [14]: type(ts.uint8.type)
Out[14]: type

In [15]: import torch

In [16]: type(torch.uint32)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-d7d700eed551> in <module>
----> 1 type(torch.uint32)

AttributeError: module 'torch' has no attribute 'uint32'

In [17]: torch.zeros(5).dtype
Out[17]: torch.float32

In [19]: type(torch.int32)
Out[19]: torch.dtype

In [21]: str(torch.int32)
Out[21]: 'torch.int32'

In [22]: torch.int32.type
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-1836c298d59e> in <module>
----> 1 torch.int32.type

AttributeError: 'torch.dtype' object has no attribute 'type'
```

I'll try to come up with something...

**Comment by jni** [comment]
Ok, this *should* be ready to review, let's see. 🤞 I've added torch and tensorstore test requirements, which I can remove/skipif if people don't like that.

I don't *love* the dtype-from-string hack I've done here, but I played around with all the relevant libraries (to wit: numpy, dask, zarr, tensorstore, and torch), and this is the only way I could come up with that works with all of them (and probably a few others). If anyone has alternate suggestions, I'm all ears.

Finally, there'll probably be a merge conflict with #2640, happy to fix whichever one comes second.

**Review by sofroniewn — APPROVED** [review]
LGTM! I'm ok with the extra test dependencies, but maybe @tlambert03 can weigh in on both code and the extra dependencies before merge if desired.

**Review by tlambert03 — APPROVED** [review]
looks good to me 👍

don't mind the test deps

**Comment by sofroniewn** [comment]
@jni looks like #2640 might be close too, i'll let you merge and handle conflict when you're ready. This is now good to go!

**Comment by sofroniewn** [comment]
@jni can you fix merge conflict when you are ready

**Comment by jni** [comment]
Locally I'm getting the following test failure that I don't understand:

```
____________________________ test_keyboard_tracking ____________________________

qtbot = <pytestqt.qtbot.QtBot object at 0x7f8a9e59a130>

    def test_keyboard_tracking(qtbot):
        sb = QtLargeIntSpinBox()
        qtbot.addWidget(sb)
        assert sb.value() == 0
        sb.setKeyboardTracking(False)
        with qtbot.assertNotEmitted(sb.valueChanged):
            sb.lineEdit().setText('20')
        assert sb.lineEdit().text() == '20'
        assert sb.value() == 0
        assert sb._pending_emit is True

        with qtbot.waitSignal(sb.valueChanged) as sgnl:
>           qtbot.keyPress(sb, Qt.Key_Enter)

napari/_qt/widgets/_tests/test_qt_large_int_spinbox.py:80:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<napari._qt.widgets.qt_large_int_spinbox.QtLargeIntSpinBox object at 0x7f8a9e5260d0>, 16777221)
kwargs = {}

    def result(*args, **kwargs):
>       return qtest_method(*args, **kwargs)
E       TypeError: 'PySide2.QtTest.QTest.keyPress' called with wrong argument types:
E         PySide2.QtTest.QTest.keyPress(QtLargeIntSpinBox, Key)
E       Supported signatures:
E         PySide2.QtTest.QTest.keyPress(PySide2.QtWidgets.QWidget, PySide2.QtCore.Qt.Key, PySide2.QtCore.Qt.KeyboardModifiers = PySide2.QtCore.Qt.KeyboardModifier.NoModifier, int = -1)
E         PySide2.QtTest.QTest.keyPress(PySide2.QtWidgets.QWidget, typing.Char, PySide2.QtCore.Qt.KeyboardModifiers = PySide2.QtCore.Qt.KeyboardModifier.NoModifier, int = -1)
E         PySide2.QtTest.QTest.keyPress(PySide2.QtGui.QWindow, PySide2.QtCore.Qt.Key, PySide2.QtCore.Qt.KeyboardModifiers = PySide2.QtCore.Qt.KeyboardModifier.NoModifier, int = -1)
E         PySide2.QtTest.QTest.keyPress(PySide2.QtGui.QWindow, typing.Char, PySide2.QtCore.Qt.KeyboardModifiers = PySide2.QtCore.Qt.KeyboardModifier.NoModifier, int = -1)

../../conda/envs/all/lib/python3.8/site-packages/pytestqt/qtbot.py:626: TypeError
```

Let's see if it reproduces on CI...

**Comment by jni** [comment]
Ooh, CI looking good...! 😊

**Comment by sofroniewn** [comment]
Merged!!
