### PR TITLE
Fix getattr obj __module__ is None in PublicOnlyProxy

### LINKED ISSUE #3785: viewer.add_points fails on proxy viewer
## 🐛 Bug

Trying to add points to a public only proxy viewer fails:

```python
import napari
from napari.utils._proxies import PublicOnlyProxy

viewer = PublicOnlyProxy(napari.Viewer())
viewer.add_points()

napari.run()
```

Gives:

```pytb
Traceback (most recent call last):
  File "/home/jni/projects/play/public-only.py", line 5, in <module>
    viewer.add_points()
  File "/home/jni/projects/napari/napari/utils/_proxies.py", line 72, in __getattr__
    return self.create(super().__getattr__(name))
  File "/home/jni/projects/napari/napari/utils/_proxies.py", line 86, in create
    if not getattr(obj, '__module__', '').startswith('napari'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

fwiw since I encountered this while trying to prepare my plugins for the plugins meeting next week, imho we should leave this experiment until after the 16th, as most people are likely to be disrupted by it. (And other npe2-related enhancements since 0.4.12 are required to work with npe2, so sticking to 0.4.12 for the meeting is not an option.)

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #3785

### CODE REVIEW

**Comment by tlambert03** [comment]
i also changed this here to revert the change from review in #3777 that went from `getattr(obj, '__module__')` from `getattr(type(obj), '__module__')` ... I think the latter is the more accurate thing here and would have avoided this regression

**Comment by gatoniel** [comment]
There is some problem with this PR. If I run 
```
viewer = napari.Viewer()
viewer.add_labels(any_label)
```
and look at it in 3D view I get the following traceback

```
RuntimeError                              Traceback (most recent call last)
d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\util\event.py in __call__(self, *args, **kwargs)
    451                     raise RuntimeError('EventEmitter loop detected!')
    452
--> 453                 self._invoke_callback(cb, event)
    454                 if event.blocked:
    455                     break

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\util\event.py in _invoke_callback(self, cb, event)
    469             cb(event)
    470         except Exception:
--> 471             _handle_exception(self.ignore_callback_errors,
    472                               self.print_callback_errors,
    473                               self, cb_event=(cb, event))

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\util\event.py in _invoke_callback(self, cb, event)
    467     def _invoke_callback(self, cb, event):
    468         try:
--> 469             cb(event)
    470         except Exception:
    471             _handle_exception(self.ignore_callback_errors,

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\scene\canvas.py in on_draw(self, event)
    216         # scheduling of further updates
    217         self._update_pending = False
--> 218         self._draw_scene()
    219
    220     def render(self, region=None, size=None, bgcolor=None, crop=None, alpha=True):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\scene\canvas.py in _draw_scene(self, bgcolor)
    275             bgcolor = self._bgcolor
    276         self.context.clear(color=bgcolor, depth=True)
--> 277         self.draw_visual(self.scene)
    278
    279     def draw_visual(self, visual, event=None):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\scene\canvas.py in draw_visual(self, visual, event)
    313                         else:
    314                             if hasattr(node, 'draw'):
--> 315                                 node.draw()
    316                                 prof.mark(str(node))
    317                 else:

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\scene\visuals.py in draw(self)
     97         if self.picking and not self.interactive:
     98             return
---> 99         self._visual_superclass.draw(self)
    100
    101

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\visuals\visual.py in draw(self)
    449         self._configure_gl_state()
    450         try:
--> 451             self._program.draw(self._vshare.draw_mode,
    452                                self._vshare.index_buffer)
    453         except Exception:

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\visuals\shaders\program.py in draw(self, *args, **kwargs)
    100         self.build_if_needed()
    101         self.update_variables()
--> 102         Program.draw(self, *args, **kwargs)
    103
    104     def build_if_needed(self):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\program.py in draw(self, mode, indices, check_error)
    524
    525         # Process GLIR commands
--> 526         canvas.context.flush_commands()

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\context.py in flush_commands(self, event)
    170                 fbo = 0
    171             self.shared.parser.parse([('CURRENT', 0, fbo)])
--> 172         self.glir.flush(self.shared.parser)
    173
    174     def set_viewport(self, *args):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\glir.py in flush(self, parser)
    577     def flush(self, parser):
    578         """Flush all current commands to the GLIR interpreter."""
--> 579         self._shared.flush(parser)
    580
    581

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\glir.py in flush(self, parser)
    499             show = self._verbose if isinstance(self._verbose, str) else None
    500             self.show(show)
--> 501         parser.parse(self._filter(self.clear(), parser))
    502
    503     def _filter(self, commands, parser):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\glir.py in parse(self, commands)
    817
    818         for command in commands:
--> 819             self._parse(command)
    820
    821     def get_object(self, id_):

d:\napari-3d-ortho-viewer\.win-napari-dev-3d-ortho-viewer\lib\site-packages\vispy\gloo\glir.py in _parse(self, command)
    773             if ob is None:
    774                 if id_ not in self._invalid_objects:
--> 775                     raise RuntimeError('Cannot %s object %i because it '
    776                                        'does not exist' % (cmd, id_))
    777                 return

RuntimeError: Cannot SIZE object 139 because it does not exist
```
As this is a PR I do not know if I should raise a new issue or not?

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
@gatoniel can you please raise a new issue? It's unclear to me whether your issue is directly related to this PR, or whether it's exposing something else.

**Comment by tlambert03** [comment]
That seems unrelated to this PR, you're not using the public only proxy there right?

**Comment by tlambert03** [comment]
Note, this code here is not invoked at all in your code example.  If you see this on main, please open an issue (it may also be worth rebuilding your environment first?)

**Comment by gatoniel** [comment]
Ok, rebuilding the environment helped.
