### ISSUE TITLE
Viewer screenshot is broken

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#159]
## 🐛 Bug

`viewer.screenshot()` gives the following error, that I think comes from us using features on `vispy` master that aren't present on their last release. We might need to backport or change our code.

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-1db5616997f4> in <module>()
----> 1 viewer.screenshot()

~/Github/napari/napari/components/_viewer/model.py in screenshot(self, region, size, bgcolor, crop)
    156         """
    157         return self._canvas.render(region=None, size=None, bgcolor=None,
--> 158                                    crop=None)
    159 
    160     def add_layer(self, layer):

TypeError: render() got an unexpected keyword argument 'crop'
```

## To Reproduce

1. Launch a viewer and add some images 
2. Run `viewer.screenshot()`

## Environment

 - napari Version (e.g., 1.0):
 - OS (e.g., Linux):
 - Python version:
 - Any other relevant information:

**Comment by kne42** [comment]
Looks like this was introduced in #88. Is having a `crop` parameter really that useful? Implementing it would require us to also backport `FrameBuffer`, a core `gloo` object, which may have unforeseen consequences.

Also, the parameters weren't properly passed to the function so that should be properly addressed too.

**Comment by sofroniewn** [comment]
I think we can drop crop for now and just get something that works - do you want to work on a PR for a fix @kne42?

**Comment by kne42** [comment]
Yeah, sounds good
