### ISSUE TITLE
Bundled app doesn't run on OSX Mavericks

### ISSUE THREAD

**Issue by adamltyson** [napari/napari#1944]
N.B. - If the answer is "we don't support anything that old", that's fine, but I thought it was worth raising
## 🐛 Bug

napari bundled app doesn't run on Mavericks (10.9.5, build 13F1911).  The dock icon briefly flashes up and then disappears. 

Running the executable from inside the package shows:
```
MC7555564:~ molly$ /Applications/napari.app/Contents/MacOS/napari ; exit;
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/napari.app/Contents/Resources/Support/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/napari.app/Contents/Resources/Support/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

/Applications/napari.app/Contents/MacOS/napari: line 5: 55772 Trace/BPT trap: 5       Support/bin/python3 -m napari
logout

[Process completed]
```

Googling suggests that `_clock_gettime` was introduced in 10.12, so presumably this won't work on 10.10 or 10.11.

## To Reproduce

Download, extract & run bundled app on OSX Mavericks. I've only tried `0.4.1rc2` (I don't have much access to this machine).

## Additional context

It would be cool if napari would run on old OSX versions. We have a lot of relatively high-powered iMacs and Mac Pro's with old OSs for compatibility with old hardware.

**Comment by sofroniewn** [comment]
For mac0S we require at least version 10.12, we used to have that in the installation tutorials, see this old version, https://github.com/napari/tutorials/blob/18b9775c682d2ce0d8331409cb6b88c5a8a850db/fundamentals/installation.md#troubleshooting but it has disappeared now. We should add back in along with a link on why. I'm pretty sure it was a fundamental Qt incompatibility for the versions of Qt that we want to use.

I'm afraid I don't think we'll be able to extend support further back, but we should update the documentation again to have this info

**Comment by adamltyson** [comment]
Cool, I figured as much. Just wanted to check. 

Definitely worth putting back in the docs, because everything installs fine on 10.9, and then nothing happens without an explanation.

**Comment by jaimergp** [comment]
Hi @adamltyson! We released a new set of installers for 0.4.15, based on conda packages. I wonder if this option works for you now? Check [napari-0.4.15-macOS-arm64.pkg](https://github.com/napari/napari/releases/download/v0.4.15/napari-0.4.15-macOS-arm64.pkg) (taken from https://github.com/napari/napari/releases/tag/v0.4.15).

**Comment by adamltyson** [comment]
Hey @jaimergp, unfortunately I can't tell you! I don't have access to the relevant machines (I don't even know if they exist anymore!). If I come across an old mac I'll test this out.

Thanks!

**Comment by jaimergp** [comment]
Thanks for your reply! `conda-forge` builds their packages on the Mavericks (10.9) SDK, so it _should_ work. Some specific packages (not sure if they are in our dependency tree) do require the 10.12 SDK, but those are rare. 

Since we cannot check right now but we have reasons to believe it can work, I'd say we can close this issue for now, @potating-potato! If it becomes a problem in the future, we can re-discuss, but I am inclined to think 10.9 is not very common nowadays, and less so moving forward.

**Comment by liu-ziyang** [comment]
thanks all! I am closing this issue for now, for anyone still seeing this with the new conda-based bundling, please feel free to reopen the issue
