### ISSUE TITLE
viewer.add_points fails on proxy viewer

### ISSUE THREAD

**Issue by jni** [napari/napari#3785]
## 🐛 Bug

Trying to add points to a public only proxy viewer fails:

```python
import napari
from napari.utils._proxies import PublicOnlyProxy

viewer = PublicOnlyProxy(napari.Viewer())
viewer.add_points()

napari.run()
```

Gives:

```pytb
Traceback (most recent call last):
  File "/home/jni/projects/play/public-only.py", line 5, in <module>
    viewer.add_points()
  File "/home/jni/projects/napari/napari/utils/_proxies.py", line 72, in __getattr__
    return self.create(super().__getattr__(name))
  File "/home/jni/projects/napari/napari/utils/_proxies.py", line 86, in create
    if not getattr(obj, '__module__', '').startswith('napari'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

fwiw since I encountered this while trying to prepare my plugins for the plugins meeting next week, imho we should leave this experiment until after the 16th, as most people are likely to be disrupted by it. (And other npe2-related enhancements since 0.4.12 are required to work with npe2, so sticking to 0.4.12 for the meeting is not an option.)

**Comment by tlambert03** [comment]
As mentioned in one on one chat, Im just fine with turning off the proxy for the next release if you want to, but this particular bug is a trivial fix

**Comment by tlambert03** [comment]
fixed in #3786

**Comment by tlambert03** [comment]
this was introduced by moving from `getattr(type(obj), '__module__')` to `getattr(obj, '__module__')` in review of #3777

**Comment by jni** [comment]
@tlambert03 yeah, I didn't think it would be a hard fix, but even if nothing else breaks and this starts working as intended, this is bound to be noisy at a time when plugin devs probably want to minimise noise. My 2c and preference, but not dogmatic about it, will just keep reporting issues when/if I encounter them.
