### ISSUE TITLE
Show Key Bindings menu option is not working in Napari 0.4.3

### ISSUE THREAD

**Issue by jmontoyam** [napari/napari#2128]
## 🐛 Bug

The Show Key Bindings menu option is not working.

## To Reproduce

1. Click on the Help menubar option
2. Then, click on Show Key Bindings

## Expected behavior

I would expect to see a list of all the available Key Bindings

## Environment

napari: 0.4.3
Platform: Linux-4.15.0-55-generic-x86_64-with-glibc2.10
Python: 3.8.3 (default, Jul 2 2020, 16:21:59) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2021.01.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.27.04
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen #1: resolution 1920x1080, scale 1.0

Plugins:
- napari_plugin_engine: 0.1.9
- svg: 0.1.4

 - Any other relevant information:

#### Error message:

/opt/Installers/python3.8/site-packages/napari/_qt/qt_viewer.py", line 576, in show_key_bindings_dialog
    dialog = QtAboutKeyBindings(self.viewer, parent=self)
  File "/opt/Installers/python3.8/site-packages/napari/_qt/dialogs/qt_about_key_bindings.py", line 67, in __init__
    theme = get_theme(self.qt_viewer.viewer.theme)
AttributeError: 'QtAboutKeyBindings' object has no attribute 'qt_viewer'

**Comment by sofroniewn** [comment]
I can reproduce this, sorry about that. We should add a test when we fix!

**Comment by nhthayer** [comment]
I was about to write up an issue on this, here is what I figured out:

The reference to the `qt_viewer` attribute looks to have been added in a recent change #2031.

If I change the following lines:
https://github.com/napari/napari/blob/ddd6715208eb02774d01c49444d45764b42b5e25/napari/_qt/dialogs/qt_about_key_bindings.py#L67
https://github.com/napari/napari/blob/ddd6715208eb02774d01c49444d45764b42b5e25/napari/_qt/dialogs/qt_about_key_bindings.py#L128
 To access the `viewer` object directly through the reference in the `QtAboutKeyBindings` object:
 ```python
         theme = get_theme(self.viewer.theme)
```
I then get a new traceback a little farther down in the code:
```bash 
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/nate/Documents/GitHub/napari/napari/_qt/qt_viewer.py", line 576, in show_key_bindings_dialog
    dialog = QtAboutKeyBindings(self.viewer, parent=self)
  File "/Users/nate/Documents/GitHub/napari/napari/_qt/dialogs/qt_about_key_bindings.py", line 100, in __init__
    self.update_active_layer()
  File "/Users/nate/Documents/GitHub/napari/napari/_qt/dialogs/qt_about_key_bindings.py", line 131, in update_active_layer
    text = get_key_bindings_summary(self.viewer.active_keymap, col=col)
AttributeError: 'Viewer' object has no attribute 'active_keymap'
 ```
With a little bit of digging, it looks like the `active_keymap` property can be accessed through:
 ```python
         text = get_key_bindings_summary(
            self.viewer.window.qt_viewer._key_map_handler.active_keymap,
            col=col
        )
 ```
After making these changes, the dialog then opens as expected. I'm a little reluctant to suggest these changes as a "fix", as I'm not sure everything else that relates to this, but hopefully this helps.

**Comment by sofroniewn** [comment]
> After making these changes, the dialog then opens as expected. I'm a little reluctant to suggest these changes as a "fix", as I'm not sure everything else that relates to this, but hopefully this helps.

Great digging! The first fix looks great and is what we want. The second one doesn't seem ideal as we have to go into private objects. One option might be to pass and attached the `key_map_handler` to the `QtAboutKeyBindings` when it is constructed inside the `QtViewer`, that seems a little more clean and robust than going `viewer.window.qt_viewer._key_map_handler`, and it seems reasonable the `QtAboutKeyBindings` should know directly about the  `key_map_handler`.

If you @nhthayer were able to submit these fixes as a PR, ideally with tests that would be amazing. I can help with the tests and help with the passing of `key_map_handler` if you need!!

**Comment by Carreau** [comment]
I came across the same issue; though the traceback is nowhere to be seen; where did you find it ?

**Comment by sofroniewn** [comment]
> I came across the same issue; though the traceback is nowhere to be seen; where did you find it ?

Surfacing tracebacks cleaning is another high priority area, the behavior right now depends a little on how you launched napari, but you can try `NAPARI_CATCH_ERRORS=0` or `NAPARI_EXIT_ON_ERROR=1`. See https://github.com/napari/napari/pull/1812#issue-513703127 for some more context

**Comment by Carreau** [comment]
Thanks ! Do you think this advice could be put on the notification toast on the lover right when triggered from "_from_error()" ?

**Comment by tlambert03** [comment]
> Do you think this advice could be put on the notification toast on the lover right when triggered from "_from_error()" ?

absolutely.  It's high up on my list of things to do to extend/clarify the API for how devs should create those toasts (in addition to simply handling exceptions).  Actually... it was starting to work on that that led me to #2075 and https://github.com/ipython/ipython/issues/10057#issuecomment-754217566 ... so if you have any interest in pairing up on that, let me know!
