### ISSUE TITLE
error with pydantic==2.0

### ISSUE THREAD

**Issue by MarkusZehner** [napari/napari#6029]
## 🐛 Bug

Installed napari 0.4.17 via conda-forge, upon calling napari in the console an error with pydantic occurred within the evented_model class.

Switching to pydantic 1.10.0 fixed this issue. 

## To Reproduce

1. % micromamba create -n napari napari
2. (napari) % napari 
Traceback (most recent call last):
  File "/Users//micromamba/envs/napari/bin/napari", line 6, in <module>
    from napari.__main__ import main
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/__main__.py", line 16, in <module>
    from .utils.translations import trans
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/utils/__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/utils/colormaps/colormap.py", line 9, in <module>
    from ..events import EventedModel
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/utils/events/__init__.py", line 15, in <module>
    from .evented_model import EventedModel
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 66, in <module>
    class EventedMetaclass(main.ModelMetaclass):
  File "/Users/markuszehner/micromamba/envs/napari/lib/python3.10/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'pydantic._migration' has no attribute 'ModelMetaclass'

## Expected behavior
Opening of the viewer.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
 Napari did not open.

 - Any other relevant information:
Works with pydantic 1.10.0

## Additional context
installed with micromamba on ARM M1.

**Comment by jni** [comment]
Yes, this is "fixed" in the upcoming 0.4.18 release in that we forbid pydantic>=2 for that release. We also hope to push an update to the 0.4.17 recipe to pin pydantic to <2 for that release. In future releases obviously we will try to migrate to support both pydantic 1 and 2. Thanks for the report, and I'm glad you already know the workaround for you! 😊

**Comment by jni** [comment]
This is fixed now @MarkusZehner, by @jaimergp in conda-forge/conda-forge-repodata-patches-feedstock#477! 🥳

**Comment by macromeer** [comment]
Downgrading to pydantic < 2 now raises a `TypeError: issubclass() arg 1 must be a class`, which seems to be related to npe2. Downgrading it to `npe2-0.4.0` solved it for me.

**Comment by psobolewskiPhD** [comment]
@macromeer Can you clarify, you want to use napari 0.4.19 but with pydantic < 2 ? and that gives an error?

**Comment by macromeer** [comment]
Yes, error of OP as well as mine can be reproduced following this: https://github.com/royerlab/aydin?tab=readme-ov-file#installation-of-aydin-in-conda

**Comment by psobolewskiPhD** [comment]
@macromeer I think we're going to need more info, because I don't see pydantic in the aydin dependencies. I also can't install it due to conflicting pins.
Assuming you installed everything via pip like those instructions, can you post the output of:
`napari --info` and
`pip show pydantic` ?

**Comment by macromeer** [comment]
```
napari --info
```
```
napari: 0.4.15
Platform: Linux-6.5.0-21-generic-x86_64-with-glibc2.35
System: Ubuntu 22.04.3 LTS
Python: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10)  [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.2.1
VisPy: 0.14.1
```
```
pip show pydantic
```
```
Name: pydantic
Version: 1.10.0
Summary: Data validation and settings management using python type hints
Home-page: https://github.com/pydantic/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: /opt/miniforge3/envs/aydin_env/lib/python3.9/site-packages
Requires: typing-extensions
Required-by: napari, npe2

```

But unfortunately, downgrading both does not work anyways, I get `<class 'TypeError'> unhashable type: 'Color'`

**Comment by Czaki** [comment]
Napari `0.4.15` is old and may be incompatible with some more recent releases of packages. 

Could you update napari to `0.4.19`?

**Comment by jni** [comment]
Indeed, unfortunately we can't afford to support old versions of napari at this time, as we struggle to maintain even the main version.

However, this does give me an idea, which is that maybe with each release we should produce a locked conda environment with all dependencies pinned, so that each version can be run long into the future with the correct dependencies for its release.

In the meantime @macromeer, if you need napari 0.4.15 specifically, you could use [pypi-timemachine](https://pypi.org/project/pypi-timemachine/) to install napari and dependencies from the date that napari 0.4.15 was released (Mar 11 2022).

**Comment by macromeer** [comment]
> Napari `0.4.15` is old and may be incompatible with some more recent releases of packages.
> 
> Could you update napari to `0.4.19`?

Aydin doesn't seem to be actively maintained, and `aydin 0.1.15 requires napari==0.4.15`, so I am kind of stuck with that version and its dependencies.

**Comment by macromeer** [comment]
> Indeed, unfortunately we can't afford to support old versions of napari at this time, as we struggle to maintain even the main version.
> 
> However, this does give me an idea, which is that maybe with each release we should produce a locked conda environment with all dependencies pinned, so that each version can be run long into the future with the correct dependencies for its release.
> 
> In the meantime @macromeer, if you need napari 0.4.15 specifically, you could use [pypi-timemachine](https://pypi.org/project/pypi-timemachine/) to install napari and dependencies from the date that napari 0.4.15 was released (Mar 11 2022).

Thanks, I will try that!

**Comment by Czaki** [comment]
Unfortunately, we provide constraints since 0.4.18, But I think that adding conda constraints may also be a good idea.

**Comment by Czaki** [comment]
For 0.4.18 a user should use constraints from this directory https://github.com/napari/napari/tree/v0.4.18/resources/constraints

**Comment by Czaki** [comment]
> I guess in general, it's `<repo root>/tree/<tag>/resources/constraints`?

yes
