### PR TITLE
Start testing on 3.12

### PR DESCRIPTION
**Pull request by Carreau**
Draft PR to see what is potentially failing and which upstream package we are waiting on.

Not 3.12 compatible yet(?):

 - [ ] torch
 - [ ] PySide6 ([PySide 6.6](https://pypi.org/project/PySide6/6.6.0/) release Oct 17th is 3.12 compatible.)
 - [ ] numba

Non-available wheels though tgz builds which can take forever:

 - [ ] tensorstore (I don't see any upsrteam issue, and a wheel has been release since 3.12 was release, but does not build on 3.12)
 - [ ] vispy
 - [x] numcodecs

Misc:

  - [ ] Setuptools need to be bumped for pip-compiled to work, but I haven't bisected the min version that we need.

```
          File "/private/var/folders/7x/x6hsdv257b3_ml15w4czp2rc0000gn/T/pip-build-env-0yq6bx8z/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
            import setuptools.version
          File "/private/var/folders/7x/x6hsdv257b3_ml15w4czp2rc0000gn/T/pip-build-env-0yq6bx8z/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
            import pkg_resources
          File "/private/var/folders/7x/x6hsdv257b3_ml15w4czp2rc0000gn/T/pip-build-env-0yq6bx8z/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
            register_finder(pkgutil.ImpImporter, find_on_path)
                            ^^^^^^^^^^^^^^^^^^^
        AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

### CODE REVIEW

**Comment by Carreau** [comment]
Asv is trying to get Python 3.11 I don't know why,

**Comment by Carreau** [comment]
@Czaki I don't understand the `Error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'resources/constraints/constraints_py3.12.txt'` while it's in this PR, any idea ?

**Comment by Czaki** [comment]
> @Czaki I don't understand the `Error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'resources/constraints/constraints_py3.12.txt'` while it's in this PR, any idea ?

It looks like installation of python 3.12 involves pip call, that is inflicted by `PIP_CONSTRAINT` env variable. 
https://github.com/napari/napari/blob/3e7eb803bd9438ce8fe7c552ba0a08211eb05914/.github/workflows/reusable_run_tox_test.yml#L50

But I do not see option to overwrite env variable only for this step, so it may need to pass full paths, not relative one.

**Comment by psobolewskiPhD** [comment]
@Carreau the python 3.12 fails https://github.com/napari/napari/actions/runs/6775591184/job/18415237126?pr=6308
look like the same issue for python 3.11:
https://github.com/napari/napari/issues/5923

Could add the skip for 3.12 like 3.11:
https://github.com/napari/napari/blob/a59cdac85136638e53d11d6c6647599a8b6f3ab7/napari/_qt/layer_controls/_tests/test_qt_layer_controls.py#L189-L197
